export interface ItineraryStop {
  time: string;
  title: string;
  titleJa: string;
  description: string;
  descriptionJa: string;
  badge?: string;
}

export interface DetailedDestination {
  id: string;
  slug: string;
  name: string;
  nameJa: string;
  subtitle: string;
  subtitleJa: string;
  region: string;
  category: string;
  categoryJa: string;
  tag: string;
  tagJa: string;
  heroImage: string;
  galleryImages: string[];
  durationText: string;
  charterHours: string;
  overview: string;
  overviewJa: string;
  whyChooseThis: string[];
  whyChooseThisJa: string[];
  alphardPrice: number;
  granacePrice: number;
  hiacePrice: number;
  alphardPriceFormatted: string;
  granacePriceFormatted: string;
  hiacePriceFormatted: string;
  itinerary: ItineraryStop[];
  inclusions: string[];
  inclusionsJa: string[];
  exclusions: string[];
  exclusionsJa: string[];
}

export const DETAILED_DESTINATIONS: Record<string, DetailedDestination> = {
  'fuji-kawaguchiko': {
    id: 'fuji-kawaguchiko',
    slug: 'fuji-kawaguchiko',
    name: 'Mount Fuji, Lake Kawaguchiko & Oshino Hakkai',
    nameJa: '富士山・河口湖・忍野八海・新倉山浅間公園',
    subtitle: 'Classic Full-Day Alpine Chauffeur Tour to Japan’s Sacred Peak',
    subtitleJa: '霊峰富士の絶景と湧水池を巡る、贅沢な専用車プライベートツアー',
    region: 'Yamanashi Prefecture',
    category: 'Mt. Fuji & Lakes',
    categoryJa: '富士山・富士五湖',
    tag: 'Iconic Japan Classic',
    tagJa: '王道・富士山観光',
    heroImage: '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    galleryImages: [
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
      '/images/winter-ski-snow-mountain-1500x1000.jpg',
      '/images/winter-ski-nagano-resort-1500x1001.jpg',
    ],
    durationText: '2.0h from Central Tokyo',
    charterHours: '10 Hours Door-to-Door Charter',
    overview:
      'Experience the pinnacle of Japanese alpine beauty with a seamless door-to-door private charter from Tokyo. Ascend through lush forests to historic viewpoints including the world-famous Chureito Pagoda, the pristine crystal-clear spring ponds of Oshino Hakkai, and picturesque Lake Kawaguchiko with panoramic views of Mount Fuji reflected across the water.',
    overviewJa:
      '東京のご宿泊ホテルから直行。五重塔と富士山が織りなす「新倉山浅間公園」、世界遺産の構成資産である湧水池「忍野八海」、四季折々の花々と逆さ富士が美しい「河口湖畔大石公園」など、富士山麓のハイライトを巡る贅沢な1日貸切プランです。',
    whyChooseThis: [
      'Private luxury VIP transport with dedicated English/Japanese speaking chauffeur',
      'Flexible pacing — spend as much time as you desire at photo stops',
      'Door-to-door hotel pick-up and luggage storage inside vehicle throughout the day',
      'Complimentary stop at local artisan Hoto noodle dining or Gotemba Premium Outlets upon request',
    ],
    whyChooseThisJa: [
      '経験豊富なプロ乗務員による完全プライベート送迎',
      'ご自身のペースで自由に見学時間を調整可能',
      'ホテル玄関から目的地まで完全ドアtoドア、車内に手荷物を預けて手ぶら観光',
      '名物ほうとうランチや御殿場アウトレットへの立ち寄りアレンジも無料対応',
    ],
    alphardPrice: 100000,
    granacePrice: 105000,
    hiacePrice: 100000,
    alphardPriceFormatted: '¥100,000',
    granacePriceFormatted: '¥105,000',
    hiacePriceFormatted: '¥100,000',
    itinerary: [
      {
        time: '08:30',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテル・ご指定場所へお迎え',
        description: 'Chauffeur meets you in the hotel lobby with your name board and helps load all day luggage into the VIP cabin.',
        descriptionJa: '乗務員がホテルロビーまでお迎えに上がり、お荷物の積載をサポート。快適な車内で出発します。',
        badge: 'Departure',
      },
      {
        time: '10:30',
        title: 'Arakurayama Sengen Park (Chureito Pagoda)',
        titleJa: '新倉山浅間公園（忠霊塔の絶景）',
        description: 'Ascend the stone steps to witness Japan’s most iconic postcard viewpoint: the crimson 5-story pagoda framed by Mount Fuji.',
        descriptionJa: '朱色の五重塔と富士山が美しく重なる、日本を代表する絶景ビューポイントへご案内。',
        badge: 'Photo Stop',
      },
      {
        time: '12:00',
        title: 'Lake Kawaguchiko & Lakeside Lunch',
        titleJa: '河口湖畔散策＆郷土料理ほうとうランチ',
        description: 'Enjoy authentic Yamanashi Hoto noodles at a charming lakeside restaurant with tranquil views of Lake Kawaguchiko.',
        descriptionJa: '河口湖の風光明媚な景色を眺めながら、名物「甲州ほうとう」などの昼食をお楽しみください。',
        badge: 'Lunch',
      },
      {
        time: '13:45',
        title: 'Oshino Hakkai Sacred Springs Village',
        titleJa: '忍野八海（世界遺産・霊峰の湧水池群）',
        description: 'Stroll through a traditional thatched-roof village fed by Mount Fuji’s filtered, crystal-clear 80-year snowmelt springs.',
        descriptionJa: '富士山の雪解け水が数十年の歳月をかけて湧き出る8つの神聖な湧水池と茅葺き屋根の集落を散策。',
        badge: 'UNESCO Heritage',
      },
      {
        time: '15:30',
        title: 'Oishi Park & Lake Promenade',
        titleJa: '大石公園・湖畔のパノラマ展望',
        description: 'Take in the unobstructed panorama across Lake Kawaguchiko with seasonal lavender, Kochia bushes, and Mt. Fuji background.',
        descriptionJa: '季節の花々と河口湖越しに広がる富士山の雄大な裾野を一望する絶景スポット。',
        badge: 'Scenic Walk',
      },
      {
        time: '18:30',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Smooth highway return to your central Tokyo hotel in relaxed leather armchair comfort.',
        descriptionJa: '夕暮れの高速道路をスムーズに走行し、ホテルまで安全にお送りいたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '10 Hours private chauffeur charter',
      'All expressway tolls (Chuo Expressway & Kawaguchiko Route)',
      'Vehicle fuel and parking fees',
      'Complimentary premium bottled water and high-speed Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '10時間専用車チャーター',
      '高速道路通行料金（中央道・富士五湖道路往復）',
      '車両燃料費・駐車場代',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Meals and personal refreshments', 'Optional admission fees (Ropeway, boat cruises)', 'Driver gratuity (optional)'],
    exclusionsJa: ['飲食代・ランチ代', 'ロープウェイ・遊覧船等の有料チケット代', 'ドライバーへのチップ（任意）'],
  },

  'hakone-lake-ashi': {
    id: 'hakone-lake-ashi',
    slug: 'hakone-lake-ashi',
    name: 'Hakone Onsen, Lake Ashi & Owakudani Valley',
    nameJa: '箱根温泉・芦ノ湖・大涌谷・箱根神社',
    subtitle: 'Private Chauffeur Tour to Japan’s Historic Hot Spring Wonderland',
    subtitleJa: '芦ノ湖の水中鳥居、大涌谷の火山地帯、名湯温泉を巡る贅沢な箱根ツアー',
    region: 'Kanagawa Prefecture',
    category: 'Hot Springs & Nature',
    categoryJa: '温泉・大自然',
    tag: 'Hot Springs & Volcano',
    tagJa: '名湯温泉と火山絶景',
    heroImage: '/images/dest-hakone-lake-ashi-1376x768.jpg',
    galleryImages: [
      '/images/dest-hakone-lake-ashi-1376x768.jpg',
      '/images/winter-ski-snow-mountain-1500x1000.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    ],
    durationText: '1.5 - 2.0h from Central Tokyo',
    charterHours: '9 Hours Door-to-Door Charter',
    overview:
      'Immerse in the geothermal beauty and samurai history of Hakone. Visit the spiritual floating red Torii gate of Hakone Shrine on Lake Ashi, ride past sulfurous volcanic plumes in Owakudani Valley, sample the longevity black eggs, and indulge in an optional private onsen day spa experience.',
    overviewJa:
      '芦ノ湖に静かに佇む「箱根神社」の平和の鳥居、今なお白い噴煙をあげる迫力の「大涌谷」、世界屈指の野外彫刻を誇る「彫刻の森美術館」、そして日帰りプライベート温泉など、箱根の魅力を余すところなく堪能できる1日プランです。',
    whyChooseThis: [
      'Direct mountain highway navigation by experienced mountain chauffeurs',
      'Skip train queues and crowded cable cars with direct private vehicle drops',
      'Optional private hot spring (kashikiri onsen) reservation assistance',
      'Luggage safely stored inside your private luxury vehicle',
    ],
    whyChooseThisJa: [
      '箱根の山道に精通したベテランドライバーによる安全快適な運行',
      '混雑する電車やバスの乗り換えなしで、各名所へダイレクトアクセス',
      '貸切日帰り温泉の手配・立ち寄りサポート',
      'スーツケースなどの手荷物を車内に載せたまま快適に観光',
    ],
    alphardPrice: 90000,
    granacePrice: 95000,
    hiacePrice: 90000,
    alphardPriceFormatted: '¥90,000',
    granacePriceFormatted: '¥95,000',
    hiacePriceFormatted: '¥90,000',
    itinerary: [
      {
        time: '08:30',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへお迎え',
        description: 'Chauffeur meets you in the lobby and begins the scenic coastal and mountain cruise via Tomei Expressway.',
        descriptionJa: '都内ホテルを出発し、東名高速道路を経由して箱根の山々へ向かいます。',
        badge: 'Departure',
      },
      {
        time: '10:30',
        title: 'Hakone Shrine & Peace Torii',
        titleJa: '箱根神社（平和の鳥居と芦ノ湖）',
        description: 'Wander ancient cedar forest paths leading to the sacred vermilion Torii standing directly in Lake Ashi.',
        descriptionJa: '樹齢数百年の杉並木を歩き、芦ノ湖に浮かぶ神秘的な水中鳥居を参拝。',
        badge: 'Shinto Shrine',
      },
      {
        time: '12:00',
        title: 'Lake Ashi Soba & Kaiseki Lunch',
        titleJa: '芦ノ湖畔ランチ（名水蕎麦・会席料理）',
        description: 'Dine on fresh Hakone spring-water Soba noodles or local trout overlooking the blue volcanic crater lake.',
        descriptionJa: '芦ノ湖を眺めながら、箱根の名水で打った手打ち蕎麦や地元食材のランチ。',
        badge: 'Lunch',
      },
      {
        time: '13:30',
        title: 'Owakudani Volcanic Valley',
        titleJa: '大涌谷（白煙立ち込める火山地帯）',
        description: 'Witness active sulfur fumaroles and taste the famed Kuro-tamago (black eggs boiled in mineral springs, granting +7 years of longevity).',
        descriptionJa: '大迫力の火山噴煙地帯を見学し、寿命が7年延びると言われる名物「黒たまご」を味わいます。',
        badge: 'Geothermal',
      },
      {
        time: '15:00',
        title: 'Hakone Open-Air Museum or Private Onsen',
        titleJa: '箱根 彫刻の森美術館 または 貸切日帰り温泉',
        description: 'Admire open-air masterworks by Picasso and Henry Moore, or soak in a private mineral hot spring bath.',
        descriptionJa: '自然と調和する名作彫刻を鑑賞、または個室のプライベート天然温泉で至福の湯浴み。',
        badge: 'Culture/Relax',
      },
      {
        time: '17:30',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Rest comfortably as your driver navigates the mountain pass and highway return back into Tokyo.',
        descriptionJa: '快適な車内でリラックスしながら、都内のホテルロビーへ帰着いたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '9 Hours private chauffeur charter',
      'All expressway toll fees (Tomei Expressway & Odawara-Atsugi Tollway)',
      'Vehicle fuel and parking fees',
      'Complimentary bottled water and Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '9時間専用車チャーター',
      '高速道路通行料金（東名高速・小田原厚木道路往復）',
      '車両燃料費・各所駐車場代',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Onsen day-use admission and towel fees', 'Lake Ashi pirate ship cruise ticket', 'Meals and personal expenses'],
    exclusionsJa: ['日帰り温泉入浴料・タオル代', '芦ノ湖海賊船乗船券', '飲食代・お土産代'],
  },

  'kamakura-enoshima': {
    id: 'kamakura-enoshima',
    slug: 'kamakura-enoshima',
    name: 'Historic Kamakura & Enoshima Shonan Coast',
    nameJa: '古都鎌倉・高徳院大仏・報国寺竹林・湘南江ノ島',
    subtitle: 'Samurai Heritage, Bamboo Temples & Pacific Ocean Coastal Drive',
    subtitleJa: '鎌倉武士の歴史、静寂の竹林茶房、江ノ電と湘南海岸を巡るプレミアムツアー',
    region: 'Kanagawa Prefecture',
    category: 'Samurai Culture & Coast',
    categoryJa: '歴史・古都・海岸',
    tag: 'Samurai & Ocean Coast',
    tagJa: '古都鎌倉と湘南海岸',
    heroImage: '/images/dest-kamakura-enoshima-1376x768.jpg',
    galleryImages: [
      '/images/dest-kamakura-enoshima-1376x768.jpg',
      '/images/dest-hakone-lake-ashi-1376x768.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    ],
    durationText: '1.0 - 1.5h from Central Tokyo',
    charterHours: '8 Hours Door-to-Door Charter',
    overview:
      'Step back in time to the 12th-century capital of Japan’s first Shogunate. Marvel at the monumental Bronze Great Buddha of Kotoku-in, sip ceremonial matcha tea amidst the towering green bamboo grove of Hokoku-ji temple, walk through Tsurugaoka Hachimangu, and drive along the sunny Pacific coastline of Enoshima and Shonan.',
    overviewJa:
      '源頼朝が開いた武家の古都・鎌倉。圧巻のスケールを誇る「高徳院 鎌倉大仏」、静寂に包まれた「報国寺」の竹林と抹茶体験、鶴岡八幡宮や小町通り、そして湘南の青い海が広がる「江ノ島」海岸線を巡る優雅な1日です。',
    whyChooseThis: [
      'Effortless navigation across Kamakura’s scattered historic temple valleys',
      'Scenic ocean highway drive along Shonan coast and Enoshima Island',
      'Customized stops for traditional matcha green tea and Kamakura boutique craft shopping',
      'Luggage safely housed inside vehicle throughout the excursion',
    ],
    whyChooseThisJa: [
      '点在する名刹や見どころを専用車でスムーズに巡回',
      '湘南海岸と江ノ島を望むオーシャンビュードライブ',
      '報国寺での本格抹茶体験や小町通りのスイーツ散策もサポート',
      'お荷物を気にせず身軽にお寺巡りを満喫',
    ],
    alphardPrice: 80000,
    granacePrice: 85000,
    hiacePrice: 80000,
    alphardPriceFormatted: '¥80,000',
    granacePriceFormatted: '¥85,000',
    hiacePriceFormatted: '¥80,000',
    itinerary: [
      {
        time: '09:00',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへお迎え',
        description: 'Chauffeur departs along the Shuto Expressway toward the historic seaside capital.',
        descriptionJa: '都内ホテルを出発し、首都高速・横浜横須賀道路を経由して鎌倉へ。',
        badge: 'Departure',
      },
      {
        time: '10:15',
        title: 'Kotoku-in Great Buddha of Kamakura',
        titleJa: '高徳院 鎌倉大仏（国宝・屋外大仏）',
        description: 'Stand in awe before the monumental 13.35-meter open-air bronze Amida Buddha cast in 1252.',
        descriptionJa: '1252年に造立された青銅の巨大な国宝・鎌倉大仏を間近で拝観。',
        badge: 'National Treasure',
      },
      {
        time: '11:30',
        title: 'Hokoku-ji Bamboo Temple & Matcha',
        titleJa: '報国寺（竹の庭と抹茶体験）',
        description: 'Listen to the rustling wind in a serene grove of over 2,000 moso bamboo stalks while sipping freshly whisked Uji matcha.',
        descriptionJa: '2,000本以上の孟宗竹が茂る幽玄な竹林を散策し、休耕庵でお抹茶を一服。',
        badge: 'Tea Ceremony',
      },
      {
        time: '12:45',
        title: 'Tsurugaoka Hachimangu & Komachi-dori',
        titleJa: '鶴岡八幡宮・小町通りランチ＆散策',
        description: 'Visit Kamakura’s spiritual heart and stroll along bustling Komachi street lined with street food and artisan crafts.',
        descriptionJa: '鎌倉の象徴である鶴岡八幡宮を参拝後、小町通りで海鮮丼ランチやスイーツの食べ歩き。',
        badge: 'Historic Town',
      },
      {
        time: '14:45',
        title: 'Shonan Coast & Enoshima Island Drive',
        titleJa: '湘南海岸ドライブ＆江ノ島展望',
        description: 'Cruise along the Pacific coastal highway Route 134 past Enoden railway crossings toward Enoshima island.',
        descriptionJa: '江ノ電や七里ヶ浜を望む海岸線を爽快にドライブし、江ノ島の絶景スポットへ。',
        badge: 'Ocean Drive',
      },
      {
        time: '17:00',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Comfortable chauffeur transfer back to your hotel in central Tokyo.',
        descriptionJa: '夕方の渋滞を巧みに避けて高速を走行し、都内ホテルへ安全にお送りいたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '8 Hours private chauffeur charter',
      'All expressway toll fees (Shuto Expressway & Yokohama-Yokosuka Road)',
      'Vehicle fuel and parking fees',
      'Complimentary bottled water and Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '8時間専用車チャーター',
      '高速道路通行料金（首都高速・横浜横須賀道路往復）',
      '車両燃料費・駐車場代',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Temple admission fees (Kotoku-in Great Buddha, Hokoku-ji)', 'Matcha tea set fee', 'Meals and drinks'],
    exclusionsJa: ['高徳院大仏拝観料・報国寺抹茶代', '飲食代・ランチ代', '個人的なお買い物代'],
  },

  'nikko-unesco': {
    id: 'nikko-unesco',
    slug: 'nikko-unesco',
    name: 'Nikko Toshogu Shrine, Kegon Falls & Lake Chuzenji',
    nameJa: '世界遺産 日光東照宮・華厳の滝・中禅寺湖・いろは坂',
    subtitle: 'UNESCO World Heritage Gold Shrine & Northern Mountain Majesty',
    subtitleJa: '徳川家康が眠る豪華絢爛な日光東照宮と落差97mの華厳の滝を巡るグランドツアー',
    region: 'Tochigi Prefecture',
    category: 'UNESCO World Heritage',
    categoryJa: '世界遺産・大自然',
    tag: 'UNESCO Gold Shrine & Falls',
    tagJa: '世界遺産と壮大な滝',
    heroImage: '/images/dest-nikko-unesco-1376x768.jpg',
    galleryImages: [
      '/images/dest-nikko-unesco-1376x768.jpg',
      '/images/winter-ski-snow-mountain-1500x1000.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    ],
    durationText: '2.5h from Central Tokyo',
    charterHours: '10 Hours Door-to-Door Charter',
    overview:
      'Journey north into the mountains of Tochigi to discover Nikko, Japan’s most opulent UNESCO World Heritage site. Explore the gold-leaf carvings of Toshogu Shrine (the mausoleum of Shogun Tokugawa Ieyasu), traverse the famous 48-hairpin Irohazaka mountain pass, view the thunderous 97-meter Kegon Waterfall, and take in the serenity of Lake Chuzenji.',
    overviewJa:
      '徳川初代将軍・家康公を祀る豪華絢爛な世界遺産「日光東照宮」。国宝・陽明門や「見ざる言わざる聞かざる」の彫刻、日本三名瀑の一つ「華厳の滝」、中禅寺湖、そして紅葉の名所「いろは坂」など、歴史と圧倒的大自然が融合した特別な1日をご案内。',
    whyChooseThis: [
      'Direct, stress-free transit past Tokyo traffic directly to mountain sanctuaries',
      'Comfortably navigate the steep 48-curve Irohazaka pass in high-performance luxury MPVs',
      'Flexible time at Toshogu Shrine with no rush',
      'Private climate-controlled executive leather seating for the full day',
    ],
    whyChooseThisJa: [
      '都内から日光まで乗り換え一切不要の完全直行',
      '急勾配のいろは坂も、高性能VIP車両で揺れ少なく快適に走行',
      '混雑を避けたスムーズなスケジュール調整と見学サポート',
      '広々としたVIP本革シートで長距離移動も疲れ知らず',
    ],
    alphardPrice: 100000,
    granacePrice: 105000,
    hiacePrice: 100000,
    alphardPriceFormatted: '¥100,000',
    granacePriceFormatted: '¥105,000',
    hiacePriceFormatted: '¥100,000',
    itinerary: [
      {
        time: '08:00',
        title: 'Early Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへ早朝お迎え',
        description: 'Chauffeur departs early to maximize your time in the mountain national park.',
        descriptionJa: '混雑を避けるため少し早めに出発し、東北自動車道・日光宇都宮道路を経由して日光へ。',
        badge: 'Departure',
      },
      {
        time: '10:30',
        title: 'Nikko Toshogu Shrine (UNESCO Heritage)',
        titleJa: '日光東照宮（世界遺産・国宝 陽明門）',
        description: 'Explore the master craftsmanship of the Yomeimon Gate, the Three Wise Monkeys, and the Sleeping Cat.',
        descriptionJa: '金箔と500以上の精密な彫刻で覆われた国宝「陽明門」や「三猿」「眠り猫」などをじっくり拝観。',
        badge: 'UNESCO',
      },
      {
        time: '12:45',
        title: 'Traditional Yuba Cuisine Lunch',
        titleJa: '日光名物「湯波（ゆば）料理」ランチ',
        description: 'Savor Nikko’s famous delicate tofu skin delicacy served in traditional Kaiseki sets.',
        descriptionJa: '日光の清流が育んだ伝統の湯波料理や手打ち蕎麦の昼食をお楽しみください。',
        badge: 'Lunch',
      },
      {
        time: '14:00',
        title: 'Irohazaka Pass & Kegon Waterfall',
        titleJa: 'いろは坂ドライブ＆華厳の滝（落差97m）',
        description: 'Ride up the famous winding pass to witness the sheer power of Japan’s most celebrated waterfall plunge.',
        descriptionJa: '48のカーブが続く絶景いろは坂を登り、エレベーターで滝壺近くから轟音響く名瀑を体感。',
        badge: 'Waterfall',
      },
      {
        time: '15:15',
        title: 'Lake Chuzenji Scenic Promenade',
        titleJa: '中禅寺湖畔散策',
        description: 'Enjoy alpine lakeside breezes and views of sacred Mount Nantai across the mirror-like waters.',
        descriptionJa: '男体山の麓に広がる美しい中禅寺湖の湖畔で、高原の澄んだ空気とカフェタイム。',
        badge: 'Lake View',
      },
      {
        time: '18:00',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Recline in comfort as your chauffeur handles the highway return into central Tokyo.',
        descriptionJa: '高速道路を快適にクルーズし、都内のホテルへお送りいたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '10 Hours private chauffeur charter',
      'All expressway toll fees (Tohoku Expressway & Nikko tollway)',
      'Vehicle fuel and parking fees',
      'Complimentary bottled water and high-speed Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '10時間専用車チャーター',
      '高速道路通行料金（東北道・日光有料道路）',
      '車両燃料費・駐車場代',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Toshogu Shrine admission ticket (¥1,300)', 'Kegon Falls elevator ticket (¥570)', 'Meals and drinks'],
    exclusionsJa: ['東照宮拝観料（1,300円）', '華厳の滝エレベーター代（570円）', '飲食代'],
  },

  'yokohama-bay': {
    id: 'yokohama-bay',
    slug: 'yokohama-bay',
    name: 'Yokohama Minato Mirai & Chinatown Harbor',
    nameJa: '横浜みなとみらい・元町中華街・三溪園・山下公園',
    subtitle: 'Cosmopolitan Bayfront, Historic Gardens & Japan’s Largest Chinatown',
    subtitleJa: '港町横浜の異国情緒、日本庭園三溪園、中華街美食と煌めくベイサイド夜景',
    region: 'Kanagawa Prefecture',
    category: 'Port City & Dining',
    categoryJa: '港町・美食・夜景',
    tag: 'Harbor Lights & Dining',
    tagJa: '港の夜景と本格中華',
    heroImage: '/images/dest-yokohama-bay-4662x5828.jpg',
    galleryImages: [
      '/images/dest-yokohama-bay-4662x5828.jpg',
      '/images/dest-kamakura-enoshima-1376x768.jpg',
      '/images/dest-hakone-lake-ashi-1376x768.jpg',
    ],
    durationText: '45m from Central Tokyo',
    charterHours: '6-8 Hours Door-to-Door Charter',
    overview:
      'Discover Japan’s iconic historic port city where East meets West. Savor authentic dim sum in the country’s largest Chinatown, wander among reconstructed Kyoto and Kamakura historic villas at Sankeien Garden, browse trendy shops at Red Brick Warehouse, and finish with dazzling illuminated night views across Minato Mirai.',
    overviewJa:
      '文明開化の歴史香る国際港湾都市・横浜。日本最大の中華街での本格点心ランチ、国の名勝「三溪園」での日本建築と庭園散策、赤レンガ倉庫、そして大観覧車や横浜ベイブリッジの煌めく夜景を贅沢に巡るツアーです。',
    whyChooseThis: [
      'Short transfer from Tokyo — perfect for easy half-day or evening leisure',
      'Doorstep drop at Chinatown restaurants and Sankeien pavilions',
      'Breathtaking illuminated night drive across Yokohama Bay Bridge',
      'Great for fine dining lovers, families, and couples',
    ],
    whyChooseThisJa: [
      '都内からわずか45分、半日〜1日のゆったりした旅程に最適',
      '中華街のレストラン前や三溪園入口までストレスなく横付け',
      'ライトアップされた横浜ベイブリッジを渡る美しい夜景クルーズ',
      'グルメ・ご家族連れ・記念日のデートにぴったり',
    ],
    alphardPrice: 60000,
    granacePrice: 65000,
    hiacePrice: 60000,
    alphardPriceFormatted: '¥60,000',
    granacePriceFormatted: '¥65,000',
    hiacePriceFormatted: '¥60,000',
    itinerary: [
      {
        time: '10:00',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへお迎え',
        description: 'Smooth drive along the Shuto Wangan Bay Expressway toward Yokohama.',
        descriptionJa: '都内を出発し、首都高速湾岸線を経由して港町横浜へ。',
        badge: 'Departure',
      },
      {
        time: '11:00',
        title: 'Sankeien Traditional Japanese Garden',
        titleJa: '三溪園（国の名勝・歴史的古建築）',
        description: 'Stroll across 175,000 sqm of traditional landscapes featuring historic pagodas and lotus ponds.',
        descriptionJa: '京都や鎌倉から移築された重要文化財の古建築と四季の花々が美しい日本庭園を散策。',
        badge: 'Japanese Garden',
      },
      {
        time: '12:45',
        title: 'Yokohama Chinatown Dim Sum Lunch',
        titleJa: '横浜中華街 点心・本格中華ランチ',
        description: 'Feast on steamed soup dumplings, Peking duck, and Cantonese delicacies in Japan’s largest Chinatown.',
        descriptionJa: '500以上の店舗がひしめく日本最大のチャイナタウンで名店の飲茶や点心を満喫。',
        badge: 'Lunch',
      },
      {
        time: '14:30',
        title: 'Red Brick Warehouse & Yamashita Park',
        titleJa: '横浜赤レンガ倉庫・山下公園',
        description: 'Explore trendy lifestyle shops in historic brick storehouses and walk along the harbor promenade.',
        descriptionJa: '明治・大正の面影を残す赤レンガ倉庫でショッピングやカフェ、海風薫る山下公園を散策。',
        badge: 'Waterfront',
      },
      {
        time: '16:30',
        title: 'Minato Mirai Skyline & Night Drive',
        titleJa: 'みなとみらい21＆ベイブリッジ夜景ドライブ',
        description: 'Take in glittering coastal views of Cosmo Clock 21 and the illuminated harbor skyline before the return journey.',
        descriptionJa: '大観覧車や高層ビル群のイルミネーション、横浜ベイブリッジの夜景を車内から贅沢に鑑賞。',
        badge: 'Night View',
      },
      {
        time: '18:00',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Chauffeur returns you directly to your hotel or evening dinner reservation in Tokyo.',
        descriptionJa: '高速道路を経て、都内のご宿泊ホテルまたはご希望のレストランまでお送りいたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: ['6-8 Hours private chauffeur charter', 'Shuto Expressway toll fees', 'Vehicle fuel & parking', 'Consumption tax (10%)'],
    inclusionsJa: ['6-8時間専用車チャーター', '首都高速道路通行料', '燃料費・駐車場代', '消費税（10%）'],
    exclusions: ['Sankeien admission ticket (¥700/adult)', 'Meals and shopping', 'Overtime fee'],
    exclusionsJa: ['三溪園入園料（大人700円）', '飲食代・お買い物代', '延長料金'],
  },

  'karuizawa-retreat': {
    id: 'karuizawa-retreat',
    slug: 'karuizawa-retreat',
    name: 'Karuizawa Royal Alpine Retreat, Waterfalls & Outlet Shopping',
    nameJa: '軽井沢・白糸の滝・雲場池・プリンスショッピングプラザ',
    subtitle: 'Japan’s Most Prestigious Mountain Resort Favored by Royalty',
    subtitleJa: 'ジョン・レノンも愛した皇室・セレブの避暑地。清流の白糸の滝と日本最大級のアウトレット',
    region: 'Nagano Prefecture',
    category: 'Highland Resort',
    categoryJa: '高原リゾート・避暑地',
    tag: 'Forest Luxury & Shopping',
    tagJa: '高原の清流とショッピング',
    heroImage: '/images/dest-karuizawa-resort-1500x1001.jpg',
    galleryImages: [
      '/images/dest-karuizawa-resort-1500x1001.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
      '/images/winter-ski-snow-mountain-1500x1000.jpg',
    ],
    durationText: '2.5h from Central Tokyo',
    charterHours: '10-12 Hours Door-to-Door Charter',
    overview:
      'Escape the city bustle to Karuizawa, Japan’s most exclusive mountain haven nestled in the highlands of Nagano. Experience the cascading curtain of Shiraito Waterfalls, the mirror reflections of Kumoba Pond, stroll along chic European boutiques in Old Karuizawa Ginza, and shop luxury brands at the Karuizawa Prince Shopping Plaza.',
    overviewJa:
      '浅間山の麓に広がる日本屈指の高級高原リゾート・軽井沢。岩肌から幾筋もの清水が流れ落ちる「白糸の滝」、白鳥が飛来する「雲場池」、お洒落なカフェが並ぶ「旧軽井沢銀座通り」、そして240店舗が集まる「軽井沢・プリンスショッピングプラザ」を巡るラグジュアリーな1日。',
    whyChooseThis: [
      'Generous luggage capacity for outlet shopping bags and winter wardrobes',
      'Smooth, scenic mountain cruise along the Joshin-etsu Expressway',
      'Flexible itinerary — divide your time between tranquil nature and luxury shopping',
      'Door-to-door VIP collection from Tokyo hotels',
    ],
    whyChooseThisJa: [
      'アウトレットでのお買い物荷物もトランクに余裕で積載可能',
      '上信越自動車道を経由した快適な高原クルージング',
      '自然散策とショッピングの時間を自由に配分可能',
      '都内ホテルから軽井沢の各スポットまで完全ドアtoドア送迎',
    ],
    alphardPrice: 90000,
    granacePrice: 95000,
    hiacePrice: 90000,
    alphardPriceFormatted: '¥90,000',
    granacePriceFormatted: '¥95,000',
    hiacePriceFormatted: '¥90,000',
    itinerary: [
      {
        time: '08:00',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへお迎え',
        description: 'Chauffeur departs early along the Kan-etsu and Joshin-etsu Expressways toward the alpine resort.',
        descriptionJa: '都内ホテルを出発し、関越・上信越自動車道を経由して爽快な軽井沢高原へ。',
        badge: 'Departure',
      },
      {
        time: '10:45',
        title: 'Shiraito Waterfall Veil',
        titleJa: '白糸の滝（清流とマイナスイオン）',
        description: 'Stroll along the curved rock face where hundreds of subterranean mineral water cascades create a pure white curtain.',
        descriptionJa: '岩肌から無数の地下水が白糸のように流れ落ちる名瀑。マイナスイオン溢れる森林浴を満喫。',
        badge: 'Nature',
      },
      {
        time: '12:15',
        title: 'Old Karuizawa Ginza & Gourmet Lunch',
        titleJa: '旧軽井沢銀座通り散策＆名店ランチ',
        description: 'Wander past historic bakery boutiques, jam shops, and enjoy lunch at a European alpine bistro.',
        descriptionJa: '歴史ある洋館や老舗ベーカリー、ジャム店が並ぶ旧軽井沢銀座通りで優雅なランチ＆散策。',
        badge: 'Lunch',
      },
      {
        time: '14:00',
        title: 'Kumoba Pond (Swan Lake)',
        titleJa: '雲場池（鏡面のような絶景湖）',
        description: 'Walk around the tranquil waters known for mirror reflections of lush alpine greenery and autumn foliage.',
        descriptionJa: '「スワンレイク」とも呼ばれる静寂の池。水面に映る新緑や紅葉のコントラストを堪能。',
        badge: 'Photo Stop',
      },
      {
        time: '15:15',
        title: 'Karuizawa Prince Shopping Plaza',
        titleJa: '軽井沢・プリンスショッピングプラザ',
        description: 'Indulge in duty-free luxury shopping across over 240 designer brand outlets set on open green lawns.',
        descriptionJa: '広大な芝生エリアに約240の有名ブランドや免税ショップが並ぶ、日本最大級のリゾートアウトレット。',
        badge: 'Shopping',
      },
      {
        time: '19:30',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Relax in executive leather seating as your driver handles the highway return with all your shopping purchases safely stowed.',
        descriptionJa: '購入されたお荷物も広々としたラゲッジに積載。快適なVIPシートでお寛ぎいただきながら都内へ帰着。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '10-12 Hours private chauffeur charter',
      'Expressway tolls and Shiraito tollway fees',
      'Vehicle fuel and parking fees',
      'Complimentary bottled water and Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '10-12時間専用車チャーター',
      '高速道路通行料・白糸ハイランドウェイ有料道路代',
      '車両燃料費・駐車場代',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Meals, shopping expenses, and personal purchases', 'Overtime fee (¥8,000/hour)'],
    exclusionsJa: ['飲食代・ショッピング代', '延長料金（8,000円/1時間）'],
  },
};

export const MULTILINGUAL_DESTINATIONS: Record<string, Record<'zh' | 'fr' | 'es', any>> = {
  'fuji-kawaguchiko': {
    zh: {
      name: '富士山・河口湖与忍野八海经典全景游',
      subtitle: '登顶日本神山圣境，尽享纯净雪水泉池与湖光山色',
      tag: '日本必游王道经典',
      category: '富士山与富士五湖',
      overview: '从东京市区专车出发，直达富士山下。打卡红塔与富士山同框的新仓山浅间公园，漫步由富士山雪水经数十年过滤涌出的忍野八海神圣清泉，在河口湖畔大石公园品味倒映在湖面的富士绝景与四季花卉。',
      region: '山梨县 富士五湖',
      durationText: '东京出发约2小时',
      whyChooseThis: [
        '配备专属专业中/日/英多语种司导，行程私密舒适',
        '时间灵活自主，各大摄影打卡点随心停留',
        '酒店门到门接送，行李全程安全寄存车内',
        '可免费安排品尝当地特色馎饦面（Hoto）或御殿场奥特莱斯',
      ],
      inclusions: [
        '10小时私人专车包车服务',
        '中央高速及富士五湖收费公路往返通行费',
        '燃油费及各大景点专属停车费',
        '车内饮用水及高速 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['餐费及个人消费', '缆车及游船门票', '超时费用 (¥8,000/小时)'],
    },
    fr: {
      name: 'Mont Fuji, Lac Kawaguchiko & Oshino Hakkai',
      subtitle: 'Excursion Privée d’Exception vers le Pic Sacré du Japon',
      tag: 'Classique Incontournable du Japon',
      category: 'Mont Fuji & Lacs',
      overview: 'Vivez l’expérience alpine japonaise par excellence avec un transfert privé porte-à-porte depuis Tokyo. Admirez la pagode Chureito, les sources pures d’Oshino Hakkai et le panorama serein du lac Kawaguchiko.',
      region: 'Préfecture de Yamanashi',
      durationText: '2h depuis le centre de Tokyo',
      whyChooseThis: [
        'Véhicule privé grand confort avec chauffeur dédié',
        'Rythme sur mesure pour profiter pleinement de chaque arrêt photo',
        'Prise en charge à votre hôtel et bagages en sécurité à bord',
        'Arrêt optionnel pour déguster les nouilles artisanales Hoto ou à Gotemba Outlets',
      ],
      inclusions: [
        '10 heures de mise à disposition avec chauffeur privé',
        'Tous les péages d’autoroute (Chuo Expressway)',
        'Carburant et frais de parking',
        'Bouteilles d’eau et Wi-Fi à bord',
        'TVA japonaise de 10% incluse',
      ],
      exclusions: ['Repas et boissons', 'Téléphérique ou croisière', 'Heures supplémentaires'],
    },
    es: {
      name: 'Monte Fuji, Lago Kawaguchiko y Manantiales Oshino',
      subtitle: 'Tour Privado Exclusivo a la Cumbre Sagrada de Japón',
      tag: 'El Clásico Inolvidable de Japón',
      category: 'Monte Fuji y Lagos',
      overview: 'Descubra la majestuosidad del Monte Fuji con un servicio puerta a puerta desde su hotel en Tokio. Visite la icónica Pagoda Chureito, los manantiales cristalinos de Oshino Hakkai y el apacible Lago Kawaguchiko.',
      region: 'Prefectura de Yamanashi',
      durationText: '2h desde el centro de Tokio',
      whyChooseThis: [
        'Transporte de lujo con chófer profesional bilingüe',
        'Itinerario flexible con todo el tiempo necesario para fotos',
        'Recogida en hotel y equipaje custodiado en el vehículo',
        'Parada opcional en restaurantes de fideos Hoto o centro Gotemba Outlets',
      ],
      inclusions: [
        '10 horas de servicio privado exclusivo',
        'Todos los peajes de autopista (Chuo Expressway)',
        'Combustible y estacionamiento',
        'Agua mineral y Wi-Fi en cabina',
        'Impuestos incluidos (10%)',
      ],
      exclusions: ['Comidas y bebidas', 'Teleférico o crucero por el lago', 'Horas extras'],
    },
  },

  'hakone-lake-ashi': {
    zh: {
      name: '箱根温泉・芦之湖水上鸟居与大涌谷地热',
      subtitle: '富士山脚下的千年古汤、火山绝景与艺术殿堂',
      tag: '极致日式私汤与火山风光',
      category: '名汤温泉与自然风貌',
      overview: '日本最负盛名的温泉度假胜地。乘专车打卡芦之湖上的箱根神社水上鸟居、白烟缭绕的大涌谷黑鸡蛋体验，以及静谧奢华的私人日归私汤温泉与雕刻之森美术馆。',
      region: '神奈川县 箱根',
      durationText: '东京出发约1.5-2小时',
      whyChooseThis: [
        '门到门私密专车接送，免去频繁换乘缆车与登山电车的繁琐',
        '私汤温泉体验安排，尊享富士山脚下的天然疗愈矿泉',
        '大涌谷与芦之湖专属停车位无缝衔接',
        '非常适合情侣度假、家庭游以及追求高品质放松的旅客',
      ],
      inclusions: [
        '9小时私人专车包车服务',
        '东名高速公路等往返通行费',
        '燃油费及箱根各景区停车费',
        '车内饮用水及高速 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['温泉入浴门票与餐费', '箱根海盗船船票', '超出时长的超时费'],
    },
    fr: {
      name: 'Hakone Onsen, Lac Ashi & Vallée d’Owakudani',
      subtitle: 'Sources Chaudes Ancestrales et Vues Panoramiques sur le Mont Fuji',
      tag: 'Expérience Onsen & Nature',
      category: 'Sources Chaudes & Culture',
      overview: 'Célèbre pour ses bains thermaux ancestraux, la porte Torii flottante du sanctuaire de Hakone sur le lac Ashi, la vallée volcanique d’Owakudani et ses musées en plein air renommés.',
      region: 'Préfecture de Kanagawa',
      durationText: '1h30 à 2h depuis Tokyo',
      whyChooseThis: [
        'Trajet direct sans correspondance de trains ou funiculaires bondés',
        'Possibilité de réserver un bain onsen privé en journée',
        'Accès direct aux belvédères du sanctuaire de Hakone et d’Owakudani',
        'Idéal pour couples, familles et amateurs d’art',
      ],
      inclusions: [
        '9 heures de mise à disposition VIP avec chauffeur',
        'Péages d’autoroute (Tomei Expressway)',
        'Carburant et parkings inclus',
        'Eau minérale et Wi-Fi à bord',
        'Taxe de 10% incluse',
      ],
      exclusions: ['Entrées aux bains thermaux et repas', 'Billet du bateau pirate', 'Heures supplémentaires'],
    },
    es: {
      name: 'Aguas Termales de Hakone, Lago Ashi y Owakudani',
      subtitle: 'Experiencia Termal de Lujo y Paisajes Naturales Frente al Monte Fuji',
      tag: 'Experiencia Prémium de Onsen',
      category: 'Aguas Termales y Paisajes',
      overview: 'Famoso por sus relajantes baños termales onsen, el Torii flotante del santuario de Hakone en el lago Ashi, el valle volcánico de Owakudani y prestigiosos museos al aire libre.',
      region: 'Prefectura de Kanagawa',
      durationText: '1.5 a 2h desde Tokio',
      whyChooseThis: [
        'Conexión directa puerta a puerta sin transbordos de tren o funicular',
        'Opción de parada en onsen privado con aguas volcánicas medicinales',
        'Aparcamiento directo en la puerta del santuario de Hakone y Owakudani',
        'Perfecto para parejas, familias y amantes del arte',
      ],
      inclusions: [
        '9 horas de servicio exclusivo con chófer privado',
        'Peajes de autopista (Tomei Expressway)',
        'Combustible y aparcamientos',
        'Agua mineral y Wi-Fi en cabina',
        'Impuestos incluidos (10%)',
      ],
      exclusions: ['Entradas a baños onsen y comidas', 'Paseos en barco por el lago Ashi', 'Horas extras'],
    },
  },

  'kamakura-enoshima': {
    zh: {
      name: '古都镰仓・高德院大佛与湘南江之岛海岸',
      subtitle: '探访武士之都千年古刹与《灌篮高手》湘南海岸',
      tag: '武士之都与唯美湘南海岸',
      category: '历史古寺与海滨风光',
      overview: '日本12世纪武家政权发源地。探访国宝镰仓青铜大佛、报国寺幽静竹林与抹茶体验、鹤冈八幡宫，并沿湘南海岸与七里滨漫步至浪漫江之岛。',
      region: '神奈川县 湘南镰仓',
      durationText: '东京出发约1-1.5小时',
      whyChooseThis: [
        '距离东京市区仅1小时车程，节奏悠闲惬意',
        '镰仓高校前站经典场景与湘南海岸公路浪漫兜风',
        '古都抹茶竹林体验与海鲜美食完美结合',
        '专车直达各景点入口，免去步行劳累',
      ],
      inclusions: [
        '8小时专属包车服务',
        '首都高与横滨横须贺道路通行费',
        '燃油费及停车费',
        '车内饮用水与 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['寺庙门票（大佛约¥300，报国寺竹林约¥400）', '餐费', '超时费'],
    },
    fr: {
      name: 'Kamakura Historique & Côte de Shonan Enoshima',
      subtitle: 'Capitale Féodale des Samouraïs, Grands Bouddhas et Plages de Shonan',
      tag: 'Histoire Samouraï & Océan',
      category: 'Temples Anciens & Littoral',
      overview: 'Ancienne capitale féodale abritant le Grand Bouddha de bronze (Kotoku-in), la bambouseraie sereine d’Hokoku-ji, le sanctuaire Tsurugaoka Hachimangu et la magnifique côte de Shonan.',
      region: 'Préfecture de Kanagawa',
      durationText: '1h à 1h30 depuis Tokyo',
      whyChooseThis: [
        'À seulement 1h de Tokyo — parfait pour une journée détendue',
        'Superbe trajet panoramique le long de l’océan Pacifique vers Enoshima',
        'Dégustation de thé matcha dans la bambouseraie historique de Hokoku-ji',
        'Dépose au plus près des sanctuaires pour un confort maximal',
      ],
      inclusions: [
        '8 heures de service privé avec chauffeur',
        'Péages d’autoroute',
        'Carburant et parkings',
        'Eau et Wi-Fi à bord',
        'Taxes incluses',
      ],
      exclusions: ['Billets d’entrée aux temples', 'Déjeuners', 'Heures supplémentaires'],
    },
    es: {
      name: 'Kamakura Histórica y Costa de Shonan Enoshima',
      subtitle: 'La Cuna del Shogunato, Santuarios Legendarios y la Costa de Shonan',
      tag: 'Tradición Samurái y Costa',
      category: 'Templos Antiguos y Playas',
      overview: 'La antigua capital del siglo XII que alberga el Gran Buda de bronce (Kotoku-in), los jardines de bambú de Hokoku-ji, el santuario Tsurugaoka Hachimangu y las playas de Shonan frente a Enoshima.',
      region: 'Prefectura de Kanagawa',
      durationText: '1 a 1.5h desde Tokio',
      whyChooseThis: [
        'A solo 1 hora de Tokio: un recorrido relajado e imprescindible',
        'Paseo panorámico por la carretera costera frente al monte Fuji y Enoshima',
        'Ceremonia de té matcha en el bosque de bambú de Hokoku-ji',
        'Acceso directo a la entrada de los santuarios sin largas caminatas',
      ],
      inclusions: [
        '8 horas de chófer privado exclusivo',
        'Peajes de autopista',
        'Combustible y estacionamientos',
        'Agua mineral y Wi-Fi',
        'Impuestos incluidos',
      ],
      exclusions: ['Entradas a templos', 'Almuerzos', 'Horas extras'],
    },
  },

  'nikko-unesco': {
    zh: {
      name: '日光东照宫・中禅寺湖与华严瀑布 (世界文化遗产)',
      subtitle: '探访日本德川幕府金碧辉煌的国宝巅峰与原始森林瀑布',
      tag: '国宝金碧辉煌世界遗产',
      category: '世界遗产与原始自然',
      overview: '供奉德川家康的日本金碧辉煌巅峰之作「日光东照宫」。游览落差近百米的日本三名瀑「华严瀑布」，海拔1269米的中禅寺湖以及著名的伊吕波红叶山道。',
      region: '栃木县 日光国立公园',
      durationText: '东京出发约2.5小时',
      whyChooseThis: [
        '日本工艺美学巅峰之作，500多处精美雕刻与纯金装饰',
        '高海拔国立公园避暑胜地，坐拥壮丽山湖与瀑布绝景',
        '经验丰富的山区司机，平稳通过著名的伊吕波48道弯',
        '专车全程直达，免去日光复杂的巴士换乘等待',
      ],
      inclusions: [
        '10小时私人豪华专车包车',
        '东北自动车道及日光宇都宫道路通行费',
        '车辆燃油费及景区停车费',
        '车内矿泉水与 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['东照宫门票 (¥1,300/位)', '华严瀑布电梯门票', '午餐及个人消费'],
    },
    fr: {
      name: 'Parc National de Nikko & Sanctuaire Toshogu (UNESCO)',
      subtitle: 'Chefs-d’œuvre Sculptés d’Or des Shoguns et Cascades Majestueuses',
      tag: 'Patrimoine Mondial de l’UNESCO',
      category: 'Trésors Nationaux & Cascades',
      overview: 'Sanctuaires spectaculaires nichés au cœur de forêts de cèdres millénaires. Visitez le somptueux sanctuaire Toshogu sculpté d’or, les chutes de Kegon et le lac Chuzenji.',
      region: 'Préfecture de Tochigi',
      durationText: '2h30 depuis Tokyo',
      whyChooseThis: [
        'Le summum de l’art architectural sacré japonais orné de feuilles d’or',
        'Parc national préservé avec chutes de 100m et lac d’altitude',
        'Conduite experte et sécurisée sur la mythique route d’Irohazaka',
        'Visite fluide sans dépendre des bus régionaux très fréquentés',
      ],
      inclusions: [
        '10 heures de service VIP avec chauffeur',
        'Tous les péages d’autoroute vers Nikko',
        'Carburant et parkings inclus',
        'Eau minérale et Wi-Fi à bord',
        'Taxes incluses (10%)',
      ],
      exclusions: ['Billet d’entrée Toshogu', 'Ascenseur des chutes de Kegon', 'Repas'],
    },
    es: {
      name: 'Parque Nacional de Nikko y Santuario Toshogu (UNESCO)',
      subtitle: 'Santuarios Dorados de los Shogunes y Cascadas en el Bosque Milenario',
      tag: 'Tesoro Patrimonio de la Humanidad',
      category: 'Patrimonio Mundial y Naturaleza',
      overview: 'Espectaculares santuarios rodeados de milenarios bosques de cedro. Admire el dorada santuario Toshogu, la imponente cascada Kegon de 100 metros y el pintoresco lago Chuzenji.',
      region: 'Prefectura de Tochigi',
      durationText: '2.5h desde Tokio',
      whyChooseThis: [
        'La máxima expresión del arte decorativo japonés con más de 500 tallas doradas',
        'Parque nacional protegido con cascadas impresionantes y lagos alpinos',
        'Chófer profesional con experiencia en las curvas de montaña de Irohazaka',
        'Transporte directo sin colas ni esperas de autobuses públicos',
      ],
      inclusions: [
        '10 horas de chófer privado exclusivo',
        'Todos los peajes de autopista a Nikko',
        'Combustible y tarifas de aparcamiento',
        'Agua mineral y Wi-Fi en cabina',
        'Impuestos incluidos (10%)',
      ],
      exclusions: ['Entradas al santuario Toshogu', 'Ascensor de la cascada Kegon', 'Comidas'],
    },
  },

  'yokohama-bay': {
    zh: {
      name: '横滨未来港21・元町中华街与三溪园庭园',
      subtitle: '感受东洋与西洋交融的浪漫港湾与璀璨海景夜市',
      tag: '港湾璀璨夜景与饕餮美食',
      category: '现代港都与历史风貌',
      overview: '日本开埠历史的现代化浪漫港湾。在日本最大的横滨中华街品尝正宗点心小笼包，漫步于移筑了京都古建筑的三溪园日本名园，傍晚畅游红砖仓库与未来港无敌海景夜景。',
      region: '神奈川县 横滨港区',
      durationText: '东京出发约45分钟',
      whyChooseThis: [
        '距离东京市区仅45分钟，半日或全日轻松游览',
        '直达中华街餐厅正门及三溪园入口',
        '夕阳与夜幕下巡游横滨海湾大桥，尽享绚烂夜景',
        '非常适合家庭聚餐、美食爱好者及情侣出行',
      ],
      inclusions: [
        '6-8小时专属包车服务',
        '首都高速公路通行费',
        '车辆燃油费及停车费',
        '消费税 (10%)',
      ],
      exclusions: ['三溪园门票 (¥700/位)', '餐饮及购物费用', '超时费'],
    },
    fr: {
      name: 'Yokohama Minato Mirai & Quartier Chinois',
      subtitle: 'Élégance Portuaire, Plus Grand Quartier Chinois et Vues Nocturnes',
      tag: 'Vue Nocturne sur la Baie & Gastronomie',
      category: 'Port Historique & Modernité',
      overview: 'Ville portuaire cosmopolite abritant le plus grand quartier chinois du Japon, le splendide jardin traditionnel Sankeien, les entrepôts historiques en brique rouge et la baie illuminée.',
      region: 'Préfecture de Kanagawa',
      durationText: '45 min depuis Tokyo',
      whyChooseThis: [
        'Trajet rapide de 45 minutes depuis Tokyo — parfait pour demi-journée ou soirée',
        'Dépose directe devant les restaurants du quartier chinois et le jardin Sankeien',
        'Traversée nocturne panoramique sur le pont Yokohama Bay Bridge',
        'Idéal pour gourmets, familles et soirées romantiques',
      ],
      inclusions: [
        '6 à 8 heures de mise à disposition avec chauffeur',
        'Péages d’autoroute Shuto',
        'Carburant et parkings',
        'Taxes incluses',
      ],
      exclusions: ['Entrée jardin Sankeien (700 ¥)', 'Repas et achats', 'Heures supplémentaires'],
    },
    es: {
      name: 'Yokohama Minato Mirai y Barrio Chino',
      subtitle: 'La Ciudad Portuaria Internacional, Gastronomía y Vistas Iluminadas',
      tag: 'Luces del Puerto y Gastronomía',
      category: 'Ciudad Portuaria y Vistas',
      overview: 'La emblemática ciudad portuaria internacional de Japón con el barrio chino más grande, el tradicional jardín Sankeien, los almacenes históricos Red Brick y el perfil iluminado de Minato Mirai.',
      region: 'Prefectura de Kanagawa',
      durationText: '45 min desde Tokio',
      whyChooseThis: [
        'A solo 45 minutos de Tokio: perfecto para medio día o noche',
        'Parada directa en la puerta de restaurantes y el jardín Sankeien',
        'Paseo nocturno sobre el emblemático puente colgante Yokohama Bay Bridge',
        'Ideal para amantes de la gastronomía, familias y parejas',
      ],
      inclusions: [
        '6-8 horas de servicio privado exclusivo',
        'Peajes de autopista',
        'Combustible y aparcamiento',
        'Impuestos incluidos',
      ],
      exclusions: ['Entrada a Sankeien (700 ¥)', 'Comidas y compras', 'Horas extras'],
    },
  },

  'karuizawa-retreat': {
    zh: {
      name: '轻井泽皇家避暑胜地・白丝瀑布与王子购物广场',
      subtitle: '日本皇室御用高原避暑胜地与顶级奥特莱斯名牌购物',
      tag: '高原清幽森林与轻奢购物',
      category: '贵族度假与森林秘境',
      overview: '约翰·列侬与日本皇室深爱的殿堂级高原避暑胜地。游览如白丝般的白丝瀑布、水面如镜的云场池、旧轻井泽银座古街，以及日本顶级轻井泽王子奥特莱斯名牌购物广场。',
      region: '长野县 轻井泽高原',
      durationText: '东京出发约2.5小时',
      whyChooseThis: [
        '宽大后备箱可容纳大量名牌购物战利品与行李',
        '上信越自动车道舒适高原巡航，避暑避寒绝佳之选',
        '自然观光与免税名牌购物自由平衡',
        '东京酒店门到门直达，轻松惬意',
      ],
      inclusions: [
        '10-12小时私人豪华专车包车',
        '关越・上信越高速通行费及白丝收费公路费',
        '燃油费及各处停车费',
        '车内矿泉水与 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['餐饮及个人购物消费', '超时费用 (¥8,000/小时)'],
    },
    fr: {
      name: 'Karuizawa Retraite Alpine & Centre Commercial Prince',
      subtitle: 'Villégiature Impériale d’Altitude, Cascades et Shopping de Luxe',
      tag: 'Forêts Luxueuses & Shopping',
      category: 'Station Alpine & Villégiature',
      overview: 'Haut lieu de villégiature privilégié par la royauté et John Lennon. Découvrez la cascade de Shiraito, l’étang Kumoba, la vieille rue de Karuizawa et le grand centre Prince Shopping Plaza.',
      region: 'Préfecture de Nagano',
      durationText: '2h30 depuis Tokyo',
      whyChooseThis: [
        'Coffre spacieux pour vos achats outlet et valises d’hiver',
        'Croisière autoroutière sereine vers les hauts plateaux de Nagano',
        'Équilibre idéal entre nature apaisante et boutiques de créateurs',
        'Prise en charge de porte à porte depuis votre hôtel de Tokyo',
      ],
      inclusions: [
        '10 à 12 heures de service VIP avec chauffeur',
        'Péages autoroutiers et route privée de Shiraito',
        'Carburant et parkings',
        'Bouteilles d’eau et Wi-Fi à bord',
        'Taxes incluses',
      ],
      exclusions: ['Repas et achats personnels', 'Heures supplémentaires'],
    },
    es: {
      name: 'Karuizawa Retiro Alpino y Centro Comercial Prince',
      subtitle: 'El Refugio Imperial de Montaña, Cascadas y Compras de Primer Nivel',
      tag: 'Bosques de Lujo y Compras',
      category: 'Resort Alpino y Descanso',
      overview: 'El refugio de montaña predilecto de la realeza y celebridades como John Lennon. Disfrute de la cascada Shiraito, el estanque Kumoba, la histórica calle Ginza de Karuizawa y el centro outlet de lujo.',
      region: 'Prefectura de Nagano',
      durationText: '2.5h desde Tokio',
      whyChooseThis: [
        'Gran capacidad de maletero para compras en outlets y equipaje',
        'Viaje panorámico y confortable por autopista hacia Nagano',
        'Combine naturaleza pura con las mejores firmas internacionales',
        'Recogida y regreso puerta a puerta en su hotel de Tokio',
      ],
      inclusions: [
        '10-12 horas de chófer privado exclusivo',
        'Peajes de autopista y carretera privada de Shiraito',
        'Combustible y aparcamientos',
        'Agua mineral y Wi-Fi en cabina',
        'Impuestos incluidos',
      ],
      exclusions: ['Comidas y compras personales', 'Horas extras'],
    },
  },
};
