export interface ItineraryStop {
  time: string;
  title: string;
  titleJa: string;
  description: string;
  descriptionJa: string;
  badge?: string;
}

export interface DetailedDestination {
  id: string;
  slug: string;
  name: string;
  nameJa: string;
  subtitle: string;
  subtitleJa: string;
  region: string;
  category: string;
  categoryJa: string;
  tag: string;
  tagJa: string;
  heroImage: string;
  galleryImages: string[];
  durationText: string;
  charterHours: string;
  overview: string;
  overviewJa: string;
  whyChooseThis: string[];
  whyChooseThisJa: string[];
  alphardPrice: number;
  granacePrice: number;
  hiacePrice: number;
  alphardPriceFormatted: string;
  granacePriceFormatted: string;
  hiacePriceFormatted: string;
  itinerary: ItineraryStop[];
  inclusions: string[];
  inclusionsJa: string[];
  exclusions: string[];
  exclusionsJa: string[];
}

export const DETAILED_DESTINATIONS: Record<string, DetailedDestination> = {
  'fuji-kawaguchiko': {
    id: 'fuji-kawaguchiko',
    slug: 'fuji-kawaguchiko',
    name: 'Mount Fuji, Lake Kawaguchiko & Oshino Hakkai',
    nameJa: '富士山・河口湖・忍野八海・新倉山浅間公園',
    subtitle: 'Classic Full-Day Alpine Chauffeur Tour to Japan’s Sacred Peak',
    subtitleJa: '霊峰富士の絶景と湧水池を巡る、贅沢な専用車プライベートツアー',
    region: 'Yamanashi Prefecture',
    category: 'Mt. Fuji & Lakes',
    categoryJa: '富士山・富士五湖',
    tag: '🗻 Iconic Japan Classic',
    tagJa: '🗻 王道・富士山観光',
    heroImage: '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    galleryImages: [
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
      '/images/winter-ski-snow-mountain-1500x1000.jpg',
      '/images/winter-ski-nagano-resort-1500x1001.jpg',
    ],
    durationText: '2.0h from Central Tokyo',
    charterHours: '10 Hours Door-to-Door Charter',
    overview:
      'Experience the pinnacle of Japanese alpine beauty with a seamless door-to-door private charter from Tokyo. Ascend through lush forests to historic viewpoints including the world-famous Chureito Pagoda, the pristine crystal-clear spring ponds of Oshino Hakkai, and picturesque Lake Kawaguchiko with panoramic views of Mount Fuji reflected across the water.',
    overviewJa:
      '東京のご宿泊ホテルから直行。五重塔と富士山が織りなす「新倉山浅間公園」、世界遺産の構成資産である湧水池「忍野八海」、四季折々の花々と逆さ富士が美しい「河口湖畔大石公園」など、富士山麓のハイライトを巡る贅沢な1日貸切プランです。',
    whyChooseThis: [
      'Private luxury VIP transport with dedicated English/Japanese speaking chauffeur',
      'Flexible pacing — spend as much time as you desire at photo stops',
      'Door-to-door hotel pick-up and luggage storage inside vehicle throughout the day',
      'Complimentary stop at local artisan Hoto noodle dining or Gotemba Premium Outlets upon request',
    ],
    whyChooseThisJa: [
      '経験豊富なプロ乗務員による完全プライベート送迎',
      'ご自身のペースで自由に見学時間を調整可能',
      'ホテル玄関から目的地まで完全ドアtoドア、車内に手荷物を預けて手ぶら観光',
      '名物ほうとうランチや御殿場アウトレットへの立ち寄りアレンジも無料対応',
    ],
    alphardPrice: 80000,
    granacePrice: 85000,
    hiacePrice: 80000,
    alphardPriceFormatted: '¥80,000',
    granacePriceFormatted: '¥85,000',
    hiacePriceFormatted: '¥80,000',
    itinerary: [
      {
        time: '08:30',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテル・ご指定場所へお迎え',
        description: 'Chauffeur meets you in the hotel lobby with your name board and helps load all day luggage into the VIP cabin.',
        descriptionJa: '乗務員がホテルロビーまでお迎えに上がり、お荷物の積載をサポート。快適な車内で出発します。',
        badge: 'Departure',
      },
      {
        time: '10:30',
        title: 'Arakurayama Sengen Park (Chureito Pagoda)',
        titleJa: '新倉山浅間公園（忠霊塔の絶景）',
        description: 'Ascend the stone steps to witness Japan’s most iconic postcard viewpoint: the crimson 5-story pagoda framed by Mount Fuji.',
        descriptionJa: '朱色の五重塔と富士山が美しく重なる、日本を代表する絶景ビューポイントへご案内。',
        badge: 'Photo Stop',
      },
      {
        time: '12:00',
        title: 'Lake Kawaguchiko & Lakeside Lunch',
        titleJa: '河口湖畔散策＆郷土料理ほうとうランチ',
        description: 'Enjoy authentic Yamanashi Hoto noodles at a charming lakeside restaurant with tranquil views of Lake Kawaguchiko.',
        descriptionJa: '河口湖の風光明媚な景色を眺めながら、名物「甲州ほうとう」などの昼食をお楽しみください。',
        badge: 'Lunch',
      },
      {
        time: '13:45',
        title: 'Oshino Hakkai Sacred Springs Village',
        titleJa: '忍野八海（世界遺産・霊峰の湧水池群）',
        description: 'Stroll through a traditional thatched-roof village fed by Mount Fuji’s filtered, crystal-clear 80-year snowmelt springs.',
        descriptionJa: '富士山の雪解け水が数十年の歳月をかけて湧き出る8つの神聖な湧水池と茅葺き屋根の集落を散策。',
        badge: 'UNESCO Heritage',
      },
      {
        time: '15:30',
        title: 'Oishi Park & Lake Craft Village',
        titleJa: '大石公園・富士大石ハナテラス',
        description: 'Relax with panoramic views across Lake Kawaguchiko, seasonal flower gardens, and local craft boutiques.',
        descriptionJa: 'ラベンダーやコキアなど四季の花々と富士山を望む絶景テラスでカフェやお土産選びを満喫。',
        badge: 'Sightseeing',
      },
      {
        time: '18:30',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Relax in reclining executive seats on the highway cruise back to your hotel in central Tokyo.',
        descriptionJa: 'リクライニングシートでゆったり寛ぎながら都内へ帰着。ご指定のレストランや空港への送迎も可能です。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '10 Hours private chauffeur charter',
      'All expressway toll fees (Chuo Expressway)',
      'Vehicle fuel and parking fees',
      'Complimentary bottled spring water & high-speed 5G Wi-Fi',
      'Meet & Greet at Tokyo hotel lobby',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '10時間専用車貸切チャーター（プロドライバー付）',
      '高速道路通行料金（中央自動車道等）',
      '車両燃料費・各観光地駐車場料金',
      '車内ミネラルウォーター＆高速5G Wi-Fi',
      'ホテルロビーでのミート＆グリート',
      '消費税（10%）',
    ],
    exclusions: [
      'Meals and personal beverage expenses',
      'Ropeway / museum admission tickets (if applicable)',
      'Overtime fees (¥8,000/hour beyond 10 hours)',
    ],
    exclusionsJa: [
      '飲食代・個人的なお土産代',
      'ロープウェイ・美術館等の入場料',
      '規定時間を超える場合の延長料金（1時間あたり8,000円）',
    ],
  },

  'hakone-lake-ashi': {
    id: 'hakone-lake-ashi',
    slug: 'hakone-lake-ashi',
    name: 'Hakone Onsen, Lake Ashi & Owakudani Valley',
    nameJa: '箱根温泉・芦ノ湖・大涌谷・箱根神社',
    subtitle: 'Private Chauffeur Tour to Japan’s Historic Hot Spring Wonderland',
    subtitleJa: '芦ノ湖の水中鳥居、大涌谷の火山地帯、名湯温泉を巡る贅沢な箱根ツアー',
    region: 'Kanagawa Prefecture',
    category: 'Hot Springs & Nature',
    categoryJa: '温泉・大自然',
    tag: '♨️ Hot Springs & Volcano',
    tagJa: '♨️ 名湯温泉と火山絶景',
    heroImage: '/images/dest-hakone-lake-ashi-1376x768.jpg',
    galleryImages: [
      '/images/dest-hakone-lake-ashi-1376x768.jpg',
      '/images/winter-ski-snow-mountain-1500x1000.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    ],
    durationText: '1.5 - 2.0h from Central Tokyo',
    charterHours: '10 Hours Door-to-Door Charter',
    overview:
      'Immerse in the geothermal beauty and samurai history of Hakone. Visit the spiritual floating red Torii gate of Hakone Shrine on Lake Ashi, ride past sulfurous volcanic plumes in Owakudani Valley, sample the longevity black eggs, and indulge in an optional private onsen day spa experience.',
    overviewJa:
      '芦ノ湖に静かに佇む「箱根神社」の平和の鳥居、今なお白い噴煙をあげる迫力の「大涌谷」、世界屈指の野外彫刻を誇る「彫刻の森美術館」、そして日帰りプライベート温泉など、箱根の魅力を余すところなく堪能できる1日プランです。',
    whyChooseThis: [
      'Direct mountain highway navigation by experienced mountain chauffeurs',
      'Skip train queues and crowded cable cars with direct private vehicle drops',
      'Optional private hot spring (kashikiri onsen) reservation assistance',
      'Luggage safely stored inside your private luxury vehicle',
    ],
    whyChooseThisJa: [
      '箱根の山道に精通したベテランドライバーによる安全快適な運行',
      '混雑する電車やバスの乗り換えなしで、各名所へダイレクトアクセス',
      '貸切日帰り温泉の手配・立ち寄りサポート',
      'スーツケースなどの手荷物を車内に載せたまま快適に観光',
    ],
    alphardPrice: 80000,
    granacePrice: 85000,
    hiacePrice: 80000,
    alphardPriceFormatted: '¥80,000',
    granacePriceFormatted: '¥85,000',
    hiacePriceFormatted: '¥80,000',
    itinerary: [
      {
        time: '08:30',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへお迎え',
        description: 'Chauffeur greets you and departs along the Tomei & Odawara-Atsugi highways towards Mount Hakone.',
        descriptionJa: 'ホテルロビーでお出迎えし、東名高速・小田原厚木道路経由で箱根へ向かいます。',
        badge: 'Departure',
      },
      {
        time: '10:30',
        title: 'Hakone Shrine & Floating Torii Gate',
        titleJa: '箱根神社・平和の鳥居（芦ノ湖畔）',
        description: 'Walk the ancient cedar paths to the serene red Torii gate standing directly inside Lake Ashi.',
        descriptionJa: '樹齢数百年の杉並木を歩き、芦ノ湖に浮かぶ朱色の「平和の鳥居」で記念撮影。',
        badge: 'Shrine',
      },
      {
        time: '11:45',
        title: 'Lake Ashi Sightseeing Cruise Viewpoint',
        titleJa: '芦ノ湖畔散策＆絶景ランチ',
        description: 'Stroll along Moto-Hakone harbor and enjoy soba noodles or European lakeside dining.',
        descriptionJa: '元箱根港周辺の絶景レストランで美味しいお蕎麦や洋食ランチをお楽しみください。',
        badge: 'Lunch',
      },
      {
        time: '13:30',
        title: 'Owakudani Volcanic Valley',
        titleJa: '大涌谷（火山噴煙と黒たまご）',
        description: 'Witness dramatic volcanic steam vents and taste the famous Kuro-tamago (black eggs boiled in mineral springs).',
        descriptionJa: '大迫力の噴煙地帯を見学し、1つ食べると7年寿命が延びると伝わる名物「黒たまご」を賞味。',
        badge: 'Volcano',
      },
      {
        time: '15:15',
        title: 'Hakone Open-Air Museum or Private Onsen',
        titleJa: '彫刻の森美術館 または 日帰り貸切温泉',
        description: 'Admire world-class outdoor masterworks by Picasso and Henry Moore, or relax in a private mineral hot spring.',
        descriptionJa: '自然と芸術が調和する野外美術館を鑑賞、または箱根屈指の名湯でプライベート温泉入浴。',
        badge: 'Onsen / Art',
      },
      {
        time: '18:30',
        title: 'Tokyo Hotel Drop-Off',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Smooth highway return to Tokyo with direct drop-off at your hotel or preferred restaurant.',
        descriptionJa: '快適な車内でリラックスしながら都内へ戻ります。ご指定のレストランへの直行も可能です。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '10 Hours private chauffeur charter',
      'All expressway toll fees (Tomei / Odawara-Atsugi)',
      'Vehicle fuel and parking fees',
      'Complimentary bottled water & onboard Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '10時間専用車貸切チャーター',
      '高速道路通行料金（東名高速・小田原厚木道路等）',
      '車両燃料費・駐車場料金',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Meals and personal expenses', 'Museum / onsen entrance fees', 'Overtime past 10 hours (¥8,000/h)'],
    exclusionsJa: ['飲食代', '美術館入場料・温泉入浴料', '規定時間超過時の延長料金（1時間8,000円）'],
  },

  'kamakura-enoshima': {
    id: 'kamakura-enoshima',
    slug: 'kamakura-enoshima',
    name: 'Historic Kamakura & Enoshima Shonan Coast',
    nameJa: '古都鎌倉・高徳院大仏・報国寺竹林・湘南江ノ島',
    subtitle: 'Samurai Heritage, Bamboo Temples & Pacific Ocean Coastal Drive',
    subtitleJa: '鎌倉武士の歴史、静寂の竹林茶房、江ノ電と湘南海岸を巡るプレミアムツアー',
    region: 'Kanagawa Prefecture',
    category: 'Samurai Culture & Coast',
    categoryJa: '歴史・古都・海岸',
    tag: '⛩️ Samurai & Ocean Coast',
    tagJa: '⛩️ 古都鎌倉と湘南海岸',
    heroImage: '/images/dest-kamakura-enoshima-1376x768.jpg',
    galleryImages: [
      '/images/dest-kamakura-enoshima-1376x768.jpg',
      '/images/dest-hakone-lake-ashi-1376x768.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    ],
    durationText: '1.0 - 1.5h from Central Tokyo',
    charterHours: '8-10 Hours Door-to-Door Charter',
    overview:
      'Step back in time to the 12th-century capital of Japan’s first Shogunate. Marvel at the monumental Bronze Great Buddha of Kotoku-in, sip ceremonial matcha tea amidst the towering green bamboo grove of Hokoku-ji temple, walk through Tsurugaoka Hachimangu, and drive along the sunny Pacific coastline of Enoshima and Shonan.',
    overviewJa:
      '源頼朝が開いた武家の古都・鎌倉。圧巻のスケールを誇る「高徳院 鎌倉大仏」、静寂に包まれた「報国寺」の竹林と抹茶体験、鶴岡八幡宮や小町通り、そして湘南の青い海が広がる「江ノ島」海岸線を巡る優雅な1日です。',
    whyChooseThis: [
      'Effortless navigation across Kamakura’s scattered historic temple valleys',
      'Scenic ocean highway drive along Shonan coast and Enoshima Island',
      'Customized stops for traditional matcha green tea and Kamakura boutique craft shopping',
      'Luggage safely housed inside vehicle throughout the excursion',
    ],
    whyChooseThisJa: [
      '点在する名刹や見どころを専用車でスムーズに巡回',
      '湘南海岸と江ノ島を望むオーシャンビュードライブ',
      '報国寺での本格抹茶体験や小町通りのスイーツ散策もサポート',
      'お荷物を気にせず身軽にお寺巡りを満喫',
    ],
    alphardPrice: 70000,
    granacePrice: 75000,
    hiacePrice: 70000,
    alphardPriceFormatted: '¥70,000',
    granacePriceFormatted: '¥75,000',
    hiacePriceFormatted: '¥70,000',
    itinerary: [
      {
        time: '09:00',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへお迎え',
        description: 'Chauffeur picks you up and cruises along the Shuto Expressway toward the historic Shonan coast.',
        descriptionJa: 'ホテルを出発し、首都高速・横浜横須賀道路経由で古都鎌倉へ向かいます。',
        badge: 'Departure',
      },
      {
        time: '10:15',
        title: 'Kotoku-in Great Buddha of Kamakura',
        titleJa: '高徳院・鎌倉大仏（国宝）',
        description: 'Admire the majestic 13-meter outdoor bronze Buddha statue cast in the year 1252.',
        descriptionJa: '1252年の造立から750年以上の歴史を刻む、国宝・鎌倉大仏の荘厳な姿を拝観。',
        badge: 'National Treasure',
      },
      {
        time: '11:30',
        title: 'Hokoku-ji Bamboo Grove & Matcha Tea',
        titleJa: '報国寺（竹の寺・本格抹茶席）',
        description: 'Walk along thousands of towering moso bamboo stalks and enjoy whisked green tea in a traditional tea garden.',
        descriptionJa: '約2,000本の孟宗竹が茂る幽玄な竹林を散策し、庵で一服の抹茶を味わう特別な時間。',
        badge: 'Culture',
      },
      {
        time: '13:00',
        title: 'Tsurugaoka Hachimangu & Komachi-dori',
        titleJa: '鶴岡八幡宮 参拝＆小町通り散策・ランチ',
        description: 'Visit Kamakura’s spiritual heart and stroll along bustling Komachi street lined with street food and artisan crafts.',
        descriptionJa: '鎌倉の象徴である鶴岡八幡宮を参拝後、小町通りで名物しらす丼や和スイーツのランチ。',
        badge: 'Lunch & Walk',
      },
      {
        time: '15:00',
        title: 'Enoshima Island & Shonan Coastal Drive',
        titleJa: '江ノ島・湘南海岸オーシャンドライブ',
        description: 'Drive across the Enoshima causeway with sweeping views of the Pacific Ocean and Mount Fuji on clear days.',
        descriptionJa: '江ノ電沿線と湘南海岸の美しい海沿いを走り、江ノ島からの雄大な太平洋を望みます。',
        badge: 'Ocean View',
      },
      {
        time: '18:00',
        title: 'Return to Tokyo',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Comfortable chauffeur transfer back to your hotel in central Tokyo.',
        descriptionJa: '夕暮れの湾岸線を抜け、都内ご指定の場所までお送りいたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '8-10 Hours private chauffeur charter',
      'All expressway toll fees',
      'Vehicle fuel and parking fees',
      'Bottled spring water and 5G Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '8〜10時間専用車チャーター',
      '高速道路通行料',
      '車両燃料費・駐車場代',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Temple admission fees (approx ¥300-¥500)', 'Meals and tea house refreshments', 'Overtime past charter duration'],
    exclusionsJa: ['拝観料（300〜500円程度）', '飲食代・抹茶代', '規定時間を超える延長料金'],
  },

  'nikko-unesco': {
    id: 'nikko-unesco',
    slug: 'nikko-unesco',
    name: 'Nikko Toshogu Shrine, Kegon Falls & Lake Chuzenji',
    nameJa: '世界遺産 日光東照宮・華厳の滝・中禅寺湖・いろは坂',
    subtitle: 'UNESCO World Heritage Gold Shrine & Northern Mountain Majesty',
    subtitleJa: '徳川家康が眠る豪華絢爛な日光東照宮と落差97mの華厳の滝を巡るグランドツアー',
    region: 'Tochigi Prefecture',
    category: 'UNESCO World Heritage',
    categoryJa: '世界遺産・大自然',
    tag: '🏯 UNESCO Gold Shrine & Falls',
    tagJa: '🏯 世界遺産と壮大な滝',
    heroImage: '/images/dest-nikko-unesco-1376x768.jpg',
    galleryImages: [
      '/images/dest-nikko-unesco-1376x768.jpg',
      '/images/winter-ski-snow-mountain-1500x1000.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    ],
    durationText: '2.5h from Central Tokyo',
    charterHours: '10-12 Hours Door-to-Door Charter',
    overview:
      'Journey north into the mountains of Tochigi to discover Nikko, Japan’s most opulent UNESCO World Heritage site. Explore the gold-leaf carvings of Toshogu Shrine (the mausoleum of Shogun Tokugawa Ieyasu), traverse the famous 48-hairpin Irohazaka mountain pass, view the thunderous 97-meter Kegon Waterfall, and take in the serenity of Lake Chuzenji.',
    overviewJa:
      '徳川初代将軍・家康公を祀る豪華絢爛な世界遺産「日光東照宮」。国宝・陽明門や「見ざる言わざる聞かざる」の彫刻、日本三名瀑の一つ「華厳の滝」、中禅寺湖、そして紅葉の名所「いろは坂」など、歴史と圧倒的大自然が融合した特別な1日をご案内。',
    whyChooseThis: [
      'Direct, stress-free transit past Tokyo traffic directly to mountain sanctuaries',
      'Comfortably navigate the steep 48-curve Irohazaka pass in high-performance luxury MPVs',
      'Flexible time at Toshogu Shrine with no rush',
      'Private climate-controlled executive leather seating for the full day',
    ],
    whyChooseThisJa: [
      '都内から日光まで乗り換え一切不要の完全直行',
      '急勾配のいろは坂も、高性能VIP車両で揺れ少なく快適に走行',
      '混雑を避けたスムーズなスケジュール調整と見学サポート',
      '広々としたVIP本革シートで長距離移動も疲れ知らず',
    ],
    alphardPrice: 90000,
    granacePrice: 95000,
    hiacePrice: 90000,
    alphardPriceFormatted: '¥90,000',
    granacePriceFormatted: '¥95,000',
    hiacePriceFormatted: '¥90,000',
    itinerary: [
      {
        time: '08:00',
        title: 'Early Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへ早朝お迎え',
        description: 'Chauffeur departs early to maximize your time in the mountain national park.',
        descriptionJa: '混雑を避けるため少し早めに出発し、東北自動車道・日光宇都宮道路を経由して日光へ。',
        badge: 'Departure',
      },
      {
        time: '10:30',
        title: 'Nikko Toshogu Shrine (UNESCO Heritage)',
        titleJa: '日光東照宮（世界遺産・国宝 陽明門）',
        description: 'Explore the master craftsmanship of the Yomeimon Gate, the Three Wise Monkeys, and the Sleeping Cat.',
        descriptionJa: '金箔と500以上の精密な彫刻で覆われた国宝「陽明門」や「三猿」「眠り猫」などをじっくり拝観。',
        badge: 'UNESCO',
      },
      {
        time: '12:45',
        title: 'Traditional Yuba Cuisine Lunch',
        titleJa: '日光名物「湯波（ゆば）料理」ランチ',
        description: 'Savor Nikko’s famous delicate tofu skin delicacy served in traditional Kaiseki sets.',
        descriptionJa: '日光の清流が育んだ伝統の湯波料理や手打ち蕎麦の昼食をお楽しみください。',
        badge: 'Lunch',
      },
      {
        time: '14:00',
        title: 'Irohazaka Pass & Kegon Waterfall',
        titleJa: 'いろは坂ドライブ＆華厳の滝（落差97m）',
        description: 'Ride up the famous winding pass to witness the sheer power of Japan’s most celebrated waterfall plunge.',
        descriptionJa: '48のカーブが続く絶景いろは坂を登り、エレベーターで滝壺近くから轟音響く名瀑を体感。',
        badge: 'Waterfall',
      },
      {
        time: '15:15',
        title: 'Lake Chuzenji Scenic Promenade',
        titleJa: '中禅寺湖畔散策',
        description: 'Enjoy alpine lakeside breezes and views of sacred Mount Nantai across the mirror-like waters.',
        descriptionJa: '男体山の麓に広がる美しい中禅寺湖の湖畔で、高原の澄んだ空気とカフェタイム。',
        badge: 'Lake View',
      },
      {
        time: '19:00',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Recline in comfort as your chauffeur handles the highway return into central Tokyo.',
        descriptionJa: '高速道路を快適にクルーズし、都内のホテルへお送りいたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '10-12 Hours private chauffeur charter',
      'All expressway toll fees (Tohoku Expressway & Nikko tollway)',
      'Vehicle fuel and parking fees',
      'Complimentary bottled water and high-speed Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '10〜12時間専用車チャーター',
      '高速道路通行料金（東北道・日光有料道路）',
      '車両燃料費・駐車場代',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Toshogu Shrine admission ticket (¥1,300)', 'Kegon Falls elevator ticket (¥570)', 'Meals and drinks'],
    exclusionsJa: ['東照宮拝観料（1,300円）', '華厳の滝エレベーター代（570円）', '飲食代'],
  },

  'yokohama-bay': {
    id: 'yokohama-bay',
    slug: 'yokohama-bay',
    name: 'Yokohama Minato Mirai, Chinatown & Sankeien Garden',
    nameJa: '横浜みなとみらい・元町中華街・三溪園・赤レンガ倉庫',
    subtitle: 'Cosmopolitan Harbor Skyline, Dim Sum Delights & Traditional Japanese Gardens',
    subtitleJa: '港町横浜の異国情緒、日本最大の中華街グルメ、名園「三溪園」と美しい夜景',
    region: 'Kanagawa Prefecture',
    category: 'City & Harbor',
    categoryJa: '港町・グルメ・夜景',
    tag: '🏮 Chinatown & Harbor Skyline',
    tagJa: '🏮 中華街とハーバー夜景',
    heroImage: '/images/dest-yokohama-bay-4662x5828.jpg',
    galleryImages: [
      '/images/dest-yokohama-bay-4662x5828.jpg',
      '/images/dest-kamakura-enoshima-1376x768.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
    ],
    durationText: '45m from Central Tokyo',
    charterHours: '6-8 Hours Door-to-Door Charter',
    overview:
      'Discover Japan’s iconic historic port city where East meets West. Savor authentic dim sum in the country’s largest Chinatown, wander among reconstructed Kyoto and Kamakura historic villas at Sankeien Garden, browse trendy shops at Red Brick Warehouse, and finish with dazzling illuminated night views across Minato Mirai.',
    overviewJa:
      '開港の歴史を刻む美しい港町・横浜。日本最大の横浜中華街で本格飲茶を堪能し、京都や鎌クラの歴史的建造物が移築された名園「三溪園」を散策。夕暮れには赤レンガ倉庫からみなとみらい21の煌めく夜景ドライブを満喫できます。',
    whyChooseThis: [
      'Short transfer from Tokyo — perfect for easy half-day or evening leisure',
      'Direct chauffeur drop-offs at Chinatown restaurant entrances and Sankeien gate',
      'Private evening night view drive across the Yokohama Bay Bridge',
      'Ideal for families, foodies, and romantic couples',
    ],
    whyChooseThisJa: [
      '都心から約45分の好アクセス、短時間でも濃密な観光が可能',
      '中華街や三溪園の入口まで専用車で横付け送迎',
      '夕暮れ・夜の横浜ベイブリッジ絶景ドライブ',
      'ファミリーやグルメ好きの方に大好評',
    ],
    alphardPrice: 60000,
    granacePrice: 65000,
    hiacePrice: 60000,
    alphardPriceFormatted: '¥60,000',
    granacePriceFormatted: '¥65,000',
    hiacePriceFormatted: '¥60,000',
    itinerary: [
      {
        time: '10:00',
        title: 'Tokyo Pick-Up',
        titleJa: '都内ホテルへお迎え',
        description: 'Smooth morning departure along the Shuto Bay Route highway.',
        descriptionJa: '首都高速湾岸線を経由し、港町横浜へ向けて出発。',
        badge: 'Departure',
      },
      {
        time: '10:45',
        title: 'Sankeien Traditional Japanese Garden',
        titleJa: '名勝 三溪園（歴史的日本建築と四季の庭園）',
        description: 'Stroll across 175,000 sqm of traditional landscapes featuring historic pagodas and lotus ponds.',
        descriptionJa: '京都や鎌倉から移築された重要文化財建築が点在する広大な日本庭園を優雅に散策。',
        badge: 'Garden',
      },
      {
        time: '12:30',
        title: 'Yokohama Chinatown & Gourmet Dim Sum',
        titleJa: '横浜中華街 散策＆本格飲茶ランチ',
        description: 'Walk through colorful paifang gates and enjoy famous soup dumplings, dim sum, and bubble tea.',
        descriptionJa: '色鮮やかな門が立ち並ぶ中華街で、名物の小籠包や本格中国料理のランチを堪能。',
        badge: 'Lunch',
      },
      {
        time: '14:30',
        title: 'Red Brick Warehouse & Yamashita Park',
        titleJa: '横浜赤レンガ倉庫・山下公園',
        description: 'Browse boutique shops in historic 1911 brick warehouses along the harbor promenade.',
        descriptionJa: '明治・大正の面影を残す赤レンガ倉庫でお買い物や港の海風を感じるカフェタイム。',
        badge: 'Harbor',
      },
      {
        time: '16:30',
        title: 'Minato Mirai Skyline & Bay Bridge Drive',
        titleJa: 'みなとみらい21＆横浜ベイブリッジ絶景ドライブ',
        description: 'Enjoy the illuminated city skyline, giant Ferris wheel, and panoramic ocean bridge views.',
        descriptionJa: '大観覧車や高層ビル群がライトアップされる黄昏時のウォーターフロントをドライブ。',
        badge: 'Night View',
      },
      {
        time: '18:00',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Quick evening return to your hotel or Tokyo dinner destination.',
        descriptionJa: '都内ホテルまたはご指定のディナー会場へお送りいたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: ['6-8 Hours private chauffeur charter', 'Shuto Expressway toll fees', 'Vehicle fuel & parking', 'Consumption tax (10%)'],
    inclusionsJa: ['6〜8時間専用車チャーター', '首都高速道路通行料', '燃料費・駐車場代', '消費税（10%）'],
    exclusions: ['Sankeien entrance ticket (¥700)', 'Meals and drinks', 'Overtime past charter duration'],
    exclusionsJa: ['三溪園入園料（700円）', '飲食代', '規定時間を超える延長料金'],
  },

  'karuizawa-retreat': {
    id: 'karuizawa-retreat',
    slug: 'karuizawa-retreat',
    name: 'Karuizawa Royal Alpine Retreat, Waterfalls & Outlet Shopping',
    nameJa: '軽井沢・白糸の滝・雲場池・プリンスショッピングプラザ',
    subtitle: 'Japan’s Most Prestigious Mountain Resort Favored by Royalty',
    subtitleJa: 'ジョン・レノンも愛した皇室・セレブの避暑地。清流の白糸の滝と日本最大級のアウトレット',
    region: 'Nagano Prefecture',
    category: 'Highland Resort',
    categoryJa: '高原リゾート・避暑地',
    tag: '🌲 Forest Luxury & Shopping',
    tagJa: '🌲 高原の清流とショッピング',
    heroImage: '/images/dest-karuizawa-resort-1500x1001.jpg',
    galleryImages: [
      '/images/dest-karuizawa-resort-1500x1001.jpg',
      '/images/dest-fuji-kawaguchiko-1376x768.jpg',
      '/images/winter-ski-snow-mountain-1500x1000.jpg',
    ],
    durationText: '2.5h from Central Tokyo',
    charterHours: '10-12 Hours Door-to-Door Charter',
    overview:
      'Escape the city bustle to Karuizawa, Japan’s most exclusive mountain haven nestled in the highlands of Nagano. Experience the cascading curtain of Shiraito Waterfalls, the mirror reflections of Kumoba Pond, stroll along chic European boutiques in Old Karuizawa Ginza, and shop luxury brands at the Karuizawa Prince Shopping Plaza.',
    overviewJa:
      '浅間山の麓に広がる日本屈指の高級高原リゾート・軽井沢。岩肌から幾筋もの清水が流れ落ちる「白糸の滝」、白鳥が飛来する「雲場池」、お洒落なカフェが並ぶ「旧軽井沢銀座通り」、そして240店舗が集まる「軽井沢・プリンスショッピングプラザ」を巡るラグジュアリーな1日。',
    whyChooseThis: [
      'Generous luggage capacity for outlet shopping bags and winter wardrobes',
      'Smooth, scenic mountain cruise along the Joshin-etsu Expressway',
      'Flexible itinerary — divide your time between tranquil nature and luxury shopping',
      'Door-to-door VIP collection from Tokyo hotels',
    ],
    whyChooseThisJa: [
      'アウトレットでのお買い物荷物もトランクに余裕で積載可能',
      '上信越自動車道を経由した快適な高原クルージング',
      '自然散策とショッピングの時間を自由に配分可能',
      '都内ホテルから軽井沢の各スポットまで完全ドアtoドア送迎',
    ],
    alphardPrice: 90000,
    granacePrice: 95000,
    hiacePrice: 90000,
    alphardPriceFormatted: '¥90,000',
    granacePriceFormatted: '¥95,000',
    hiacePriceFormatted: '¥90,000',
    itinerary: [
      {
        time: '08:00',
        title: 'Tokyo Hotel Pick-Up',
        titleJa: '都内ホテルへお迎え',
        description: 'Chauffeur departs along the Kan-etsu & Joshin-etsu Expressways toward the Nagano highlands.',
        descriptionJa: '関越自動車道・上信越自動車道を経由して信州・軽井沢へ向けて出発。',
        badge: 'Departure',
      },
      {
        time: '10:30',
        title: 'Shiraito Waterfalls (Curtain of White Silk)',
        titleJa: '白糸の滝（岩肌から湧き出る清流のカーテン）',
        description: 'Walk through fresh pine air to see natural underground spring waters cascading across a 70-meter wide rock face.',
        descriptionJa: 'マイナスイオン溢れる白糸ハイランドウェイを走り、幅70mにわたって湧水が糸のように流れ落ちる名瀑を散策。',
        badge: 'Nature',
      },
      {
        time: '12:00',
        title: 'Old Karuizawa Ginza & French Bakeries',
        titleJa: '旧軽井沢銀座通り＆ランチ',
        description: 'Stroll along the historic summer street and enjoy lunch at a classic French bistro or wood-fired pizza cafe.',
        descriptionJa: '歴史ある教会や洋館、老舗ベーカリー、ジャム店が並ぶ旧軽井沢銀座で優雅なランチ＆散策。',
        badge: 'Lunch',
      },
      {
        time: '13:45',
        title: 'Kumoba Pond (Swan Lake)',
        titleJa: '雲場池（四季折々の水鏡）',
        description: 'Enjoy a leisurely walk around the tranquil pond reflecting vibrant green foliage or brilliant autumn maples.',
        descriptionJa: '水面に浅間山や木々が鮮やかに映り込む「スワンレイク」周辺の木漏れ日プロムナードを散策。',
        badge: 'Scenic Walk',
      },
      {
        time: '15:00',
        title: 'Karuizawa Prince Shopping Plaza Outlet',
        titleJa: '軽井沢・プリンスショッピングプラザ',
        description: 'Shop luxury international designer brands, outdoor lifestyle gear, and duty-free specialty shops.',
        descriptionJa: '広大な芝生広場を囲む日本最大級のリゾート型アウトレットで免税ショッピングを満喫。',
        badge: 'Shopping',
      },
      {
        time: '19:30',
        title: 'Return to Tokyo Hotel',
        titleJa: '都内ホテル・空港へご到着',
        description: 'Relax in executive leather seats as your chauffeur loads all shopping bags and delivers you home.',
        descriptionJa: 'お買い物の荷物を載せたまま、ゆったりと都内ホテルまでお送りいたします。',
        badge: 'Arrival',
      },
    ],
    inclusions: [
      '10-12 Hours private chauffeur charter',
      'All expressway tolls (Kan-etsu & Joshin-etsu) & Shiraito toll road',
      'Vehicle fuel and parking fees',
      'Bottled spring water and high-speed Wi-Fi',
      'Consumption tax (10%)',
    ],
    inclusionsJa: [
      '10〜12時間専用車チャーター',
      '高速道路通行料金（関越道・上信越道・白糸ハイランドウェイ）',
      '車両燃料費・駐車場代',
      '車内ミネラルウォーター＆Wi-Fi',
      '消費税（10%）',
    ],
    exclusions: ['Meals and personal shopping expenses', 'Overtime past charter duration (¥8,000/h)'],
    exclusionsJa: ['飲食代・ショッピング代', '規定時間を超える延長料金'],
  },
};

// Aliases for slug compatibility
DETAILED_DESTINATIONS['hakone-onsen'] = DETAILED_DESTINATIONS['hakone-lake-ashi'];
DETAILED_DESTINATIONS['nikko-world-heritage'] = DETAILED_DESTINATIONS['nikko-unesco'];
DETAILED_DESTINATIONS['yokohama-city'] = DETAILED_DESTINATIONS['yokohama-bay'];

export interface LocalizedDestinationContent {
  name: string;
  subtitle: string;
  tag: string;
  category: string;
  overview: string;
  region: string;
  durationText: string;
  whyChooseThis: string[];
  inclusions: string[];
  exclusions: string[];
}

export const MULTILINGUAL_DESTINATIONS: Record<
  string,
  Record<'zh' | 'fr' | 'es', LocalizedDestinationContent>
> = {
  'fuji-kawaguchiko': {
    zh: {
      name: '富士山・河口湖・忍野八海与新仓山浅间公园',
      subtitle: '探访日本神圣之巅的经典全日专属包车游',
      tag: '⭐ 经典必游人气No.1',
      category: '绝景与世界文化遗产',
      overview: '从东京市区酒店直达富士山脚下。游览明信片同款的新仓山浅间公园（五重塔与富士山同框）、世界遗产忍野八海的清澈泉水池，以及四季花海与逆富士绝景的河口湖大石公园。',
      region: '山梨县 富士五湖',
      durationText: '东京出发约2小时',
      whyChooseThis: [
        '专业双语司机提供全程私人专属尊贵包车服务',
        '行程时间自由随心，在各拍照点尽情停留',
        '酒店大堂上门接送，全程车内安全存放行李，轻松畅游',
        '可应要求免费安排品尝当地特色馎饦面或御殿场奥莱购物',
      ],
      inclusions: [
        '10小时专属豪华专车包车服务（含资深司机）',
        '中央自动车道等全程高速公路通行费',
        '车辆燃油费及各景区停车费',
        '车内免费矿泉水与高速 5G Wi-Fi',
        '东京酒店大堂举牌迎接服务',
        '日本消费税 (10%)',
      ],
      exclusions: ['餐费与个人消费', '超出预定包车时长的超时费 (¥8,000/小时)'],
    },
    fr: {
      name: 'Mont Fuji, Lac Kawaguchiko & Oshino Hakkai',
      subtitle: 'Circuit d’une Journée Complète avec Chauffeur au Cœur du Japon Sacré',
      tag: '⭐ Circuit Classique Incontournable',
      category: 'Nature & Patrimoine Mondial',
      overview: 'Découvrez la majesté du Mont Fuji avec un chauffeur privé de porte-à-porte depuis Tokyo. Visitez la célèbre pagode Chureito, les sources cristallines d’Oshino Hakkai et le parc Oishi au bord du lac Kawaguchiko.',
      region: 'Préfecture de Yamanashi',
      durationText: '2h de route depuis Tokyo',
      whyChooseThis: [
        'Transport VIP privé avec chauffeur professionnel bilingue',
        'Rythme sur mesure — prenez tout votre temps pour les séances photos',
        'Prise en charge à votre hôtel avec bagages sécurisés à bord',
        'Arrêts gastronomiques ou shopping à Gotemba sur simple demande',
      ],
      inclusions: [
        '10 heures de mise à disposition d’un véhicule de prestige avec chauffeur',
        'Tous les péages d’autoroute (Chuo Expressway)',
        'Carburant et frais de stationnement sur les sites',
        'Bouteilles d’eau minérale et Wi-Fi 5G haute vitesse',
        'Accueil personnalisé dans le hall de votre hôtel',
        'Taxe de consommation japonaise (10%)',
      ],
      exclusions: ['Repas et dépenses personnelles', 'Heures supplémentaires (8 000 ¥/h)'],
    },
    es: {
      name: 'Monte Fuji, Lago Kawaguchiko y Oshino Hakkai',
      subtitle: 'Tour Clásico de Día Completo con Chófer Privado a la Montaña Sagrada',
      tag: '⭐ El Tour Clásico Más Popular',
      category: 'Naturaleza y Patrimonio Mundial',
      overview: 'Disfrute de la belleza incomparable del Monte Fuji con un chófer privado desde Tokio. Visite la icónica pagoda Chureito, los manantiales sagrados de Oshino Hakkai y las vistas panorámicas del lago Kawaguchiko.',
      region: 'Prefectura de Yamanashi',
      durationText: '2h desde el centro de Tokio',
      whyChooseThis: [
        'Transporte prémium exclusivo con chófer profesional bilingüe',
        'Itinerario flexible a su propio ritmo en cada parada fotográfica',
        'Recogida en la puerta de su hotel y equipaje protegido en el vehículo',
        'Parada de cortesía para almuerzo tradicional o compras en Gotemba Outlet',
      ],
      inclusions: [
        '10 horas de servicio de chófer privado exclusivo',
        'Todos los peajes de autopista (Chuo Expressway)',
        'Combustible y aparcamiento en todos los destinos',
        'Agua embotellada de cortesía y Wi-Fi 5G de alta velocidad',
        'Bienvenida personalizada en el vestíbulo de su hotel',
        'Impuesto sobre el consumo (10%)',
      ],
      exclusions: ['Comidas y gastos personales', 'Horas extras fuera del horario acordado (¥8,000/h)'],
    },
  },

  'hakone-lake-ashi': {
    zh: {
      name: '箱根温泉・芦之湖海盗船与大涌谷火山谷',
      subtitle: '富士箱根伊豆国立公园的极致温泉与自然美景之旅',
      tag: '♨️ 顶级日式温泉与自然秘境',
      category: '温泉度假与艺术之境',
      overview: '日本最著名的温泉胜地。乘专车打卡芦之湖上的箱根神社水上鸟居、白烟缭绕的大涌谷黑鸡蛋体验，以及静谧奢华的私人日归私汤温泉与雕刻之森美术馆。',
      region: '神奈川县 箱根',
      durationText: '东京出发约1.5-2小时',
      whyChooseThis: [
        '门到门私密专车接送，免去频繁换乘缆车与登山电车的繁琐',
        '私汤温泉体验安排，尊享富士山脚下的天然疗愈矿泉',
        '大涌谷与芦之湖专属停车位无缝衔接',
        '非常适合情侣度假、家庭游以及追求高品质放松的旅客',
      ],
      inclusions: [
        '10小时私人专车包车服务',
        '东名高速公路等往返通行费',
        '燃油费及箱根各景区停车费',
        '车内饮用水及高速 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['温泉入浴门票与餐费', '箱根海盗船船票', '超出时长的超时费'],
    },
    fr: {
      name: 'Hakone Onsen, Lac Ashi & Vallée d’Owakudani',
      subtitle: 'Sources Chaudes Ancestrales et Vues Panoramiques sur le Mont Fuji',
      tag: '♨️ Expérience Onsen & Nature',
      category: 'Sources Chaudes & Culture',
      overview: 'Célèbre pour ses bains thermaux ancestraux, la porte Torii flottante du sanctuaire de Hakone sur le lac Ashi, la vallée volcanique d’Owakudani et ses musées en plein air renommés.',
      region: 'Préfecture de Kanagawa',
      durationText: '1h30 à 2h depuis Tokyo',
      whyChooseThis: [
        'Trajet direct sans correspondance de trains ou funiculaires bondés',
        'Possibilité de réserver un bain onsen privé en journée',
        'Accès direct aux belvédères du sanctuaire de Hakone et d’Owakudani',
        'Idéal pour couples, familles et amateurs d’art',
      ],
      inclusions: [
        '10 heures de mise à disposition VIP avec chauffeur',
        'Péages d’autoroute (Tomei Expressway)',
        'Carburant et parkings inclus',
        'Eau minérale et Wi-Fi à bord',
        'Taxe de 10% incluse',
      ],
      exclusions: ['Entrées aux bains thermaux et repas', 'Billet du bateau pirate', 'Heures supplémentaires'],
    },
    es: {
      name: 'Aguas Termales de Hakone, Lago Ashi y Owakudani',
      subtitle: 'Experiencia Termal de Lujo y Paisajes Naturales Frente al Monte Fuji',
      tag: '♨️ Experiencia Prémium de Onsen',
      category: 'Aguas Termales y Paisajes',
      overview: 'Famoso por sus relajantes baños termales onsen, el Torii flotante del santuario de Hakone en el lago Ashi, el valle volcánico de Owakudani y prestigiosos museos al aire libre.',
      region: 'Prefectura de Kanagawa',
      durationText: '1.5 a 2h desde Tokio',
      whyChooseThis: [
        'Conexión directa puerta a puerta sin transbordos de tren o funicular',
        'Opción de parada en onsen privado con aguas volcánicas medicinales',
        'Aparcamiento directo en la puerta del santuario de Hakone y Owakudani',
        'Perfecto para parejas, familias y amantes del arte',
      ],
      inclusions: [
        '10 horas de servicio exclusivo con chófer privado',
        'Peajes de autopista (Tomei Expressway)',
        'Combustible y aparcamientos',
        'Agua mineral y Wi-Fi en cabina',
        'Impuestos incluidos (10%)',
      ],
      exclusions: ['Entradas a baños onsen y comidas', 'Paseos en barco por el lago Ashi', 'Horas extras'],
    },
  },

  'kamakura-enoshima': {
    zh: {
      name: '古都镰仓・高德院大佛与湘南江之岛海岸',
      subtitle: '探访武士之都千年古刹与《灌篮高手》湘南海岸',
      tag: '⛩️ 武士之都与唯美湘南海岸',
      category: '历史古寺与海滨风光',
      overview: '日本12世纪武家政权发源地。探访国宝镰仓青铜大佛、报国寺幽静竹林与抹茶体验、鹤冈八幡宫，并沿湘南海岸与七里滨漫步至浪漫江之岛。',
      region: '神奈川县 湘南镰仓',
      durationText: '东京出发约1-1.5小时',
      whyChooseThis: [
        '距离东京市区仅1小时车程，节奏悠闲惬意',
        '镰仓高校前站经典场景与湘南海岸公路浪漫兜风',
        '古都抹茶竹林体验与海鲜美食完美结合',
        '专车直达各景点入口，免去步行劳累',
      ],
      inclusions: [
        '8-10小时专属包车服务',
        '首都高与横滨横须贺道路通行费',
        '燃油费及停车费',
        '车内饮用水与 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['寺庙门票（大佛约¥300，报国寺竹林约¥400）', '餐费', '超时费'],
    },
    fr: {
      name: 'Kamakura Historique & Côte de Shonan Enoshima',
      subtitle: 'Capitale Féodale des Samouraïs, Grands Bouddhas et Plages de Shonan',
      tag: '⛩️ Histoire Samouraï & Océan',
      category: 'Temples Anciens & Littoral',
      overview: 'Ancienne capitale féodale abritant le Grand Bouddha de bronze (Kotoku-in), la bambouseraie sereine d’Hokoku-ji, le sanctuaire Tsurugaoka Hachimangu et la magnifique côte de Shonan.',
      region: 'Préfecture de Kanagawa',
      durationText: '1h à 1h30 depuis Tokyo',
      whyChooseThis: [
        'À seulement 1h de Tokyo — parfait pour une journée détendue',
        'Superbe trajet panoramique le long de l’océan Pacifique vers Enoshima',
        'Dégustation de thé matcha dans la bambouseraie historique de Hokoku-ji',
        'Dépose au plus près des sanctuaires pour un confort maximal',
      ],
      inclusions: [
        '8 à 10 heures de service privé avec chauffeur',
        'Péages d’autoroute',
        'Carburant et parkings',
        'Eau et Wi-Fi à bord',
        'Taxes incluses',
      ],
      exclusions: ['Billets d’entrée aux temples', 'Déjeuners', 'Heures supplémentaires'],
    },
    es: {
      name: 'Kamakura Histórica y Costa de Shonan Enoshima',
      subtitle: 'La Cuna del Shogunato, Santuarios Legendarios y la Costa de Shonan',
      tag: '⛩️ Tradición Samurái y Costa',
      category: 'Templos Antiguos y Playas',
      overview: 'La antigua capital del siglo XII que alberga el Gran Buda de bronce (Kotoku-in), los jardines de bambú de Hokoku-ji, el santuario Tsurugaoka Hachimangu y las playas de Shonan frente a Enoshima.',
      region: 'Prefectura de Kanagawa',
      durationText: '1 a 1.5h desde Tokio',
      whyChooseThis: [
        'A solo 1 hora de Tokio: un recorrido relajado e imprescindible',
        'Paseo panorámico por la carretera costera frente al monte Fuji y Enoshima',
        'Ceremonia de té matcha en el bosque de bambú de Hokoku-ji',
        'Acceso directo a la entrada de los santuarios sin largas caminatas',
      ],
      inclusions: [
        '8-10 horas de chófer privado exclusivo',
        'Peajes de autopista',
        'Combustible y estacionamientos',
        'Agua mineral y Wi-Fi',
        'Impuestos incluidos',
      ],
      exclusions: ['Entradas a templos', 'Almuerzos', 'Horas extras'],
    },
  },

  'nikko-unesco': {
    zh: {
      name: '日光东照宫・中禅寺湖与华严瀑布 (世界文化遗产)',
      subtitle: '探访日本德川幕府金碧辉煌的国宝巅峰与原始森林瀑布',
      tag: '🏯 国宝金碧辉煌世界遗产',
      category: '世界遗产与原始自然',
      overview: '供奉德川家康的日本金碧辉煌巅峰之作「日光东照宫」。游览落差近百米的日本三名瀑「华严瀑布」，海拔1269米的中禅寺湖以及著名的伊吕波红叶山道。',
      region: '栃木县 日光国立公园',
      durationText: '东京出发约2.5小时',
      whyChooseThis: [
        '日本工艺美学巅峰之作，500多处精美雕刻与纯金装饰',
        '高海拔国立公园避暑胜地，坐拥壮丽山湖与瀑布绝景',
        '经验丰富的山区司机，平稳通过著名的伊吕波48道弯',
        '专车全程直达，免去日光复杂的巴士换乘等待',
      ],
      inclusions: [
        '10-12小时私人豪华专车包车',
        '东北自动车道及日光宇都宫道路通行费',
        '车辆燃油费及景区停车费',
        '车内矿泉水与 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['东照宫门票 (¥1,300/位)', '华严瀑布电梯门票', '午餐及个人消费'],
    },
    fr: {
      name: 'Parc National de Nikko & Sanctuaire Toshogu (UNESCO)',
      subtitle: 'Chefs-d’œuvre Sculptés d’Or des Shoguns et Cascades Majestueuses',
      tag: '🏯 Patrimoine Mondial de l’UNESCO',
      category: 'Trésors Nationaux & Cascades',
      overview: 'Sanctuaires spectaculaires nichés au cœur de forêts de cèdres millénaires. Visitez le somptueux sanctuaire Toshogu sculpté d’or, les chutes de Kegon et le lac Chuzenji.',
      region: 'Préfecture de Tochigi',
      durationText: '2h30 depuis Tokyo',
      whyChooseThis: [
        'Le summum de l’art architectural sacré japonais orné de feuilles d’or',
        'Parc national préservé avec chutes de 100m et lac d’altitude',
        'Conduite experte et sécurisée sur la mythique route d’Irohazaka',
        'Visite fluide sans dépendre des bus régionaux très fréquentés',
      ],
      inclusions: [
        '10 à 12 heures de service VIP avec chauffeur',
        'Tous les péages d’autoroute vers Nikko',
        'Carburant et parkings inclus',
        'Eau minérale et Wi-Fi à bord',
        'Taxes incluses (10%)',
      ],
      exclusions: ['Billet d’entrée Toshogu', 'Ascenseur des chutes de Kegon', 'Repas'],
    },
    es: {
      name: 'Parque Nacional de Nikko y Santuario Toshogu (UNESCO)',
      subtitle: 'Santuarios Dorados de los Shogunes y Cascadas en el Bosque Milenario',
      tag: '🏯 Tesoro Patrimonio de la Humanidad',
      category: 'Patrimonio Mundial y Naturaleza',
      overview: 'Espectaculares santuarios rodeados de milenarios bosques de cedro. Admire el dorada santuario Toshogu, la imponente cascada Kegon de 100 metros y el pintoresco lago Chuzenji.',
      region: 'Prefectura de Tochigi',
      durationText: '2.5h desde Tokio',
      whyChooseThis: [
        'La máxima expresión del arte decorativo japonés con más de 500 tallas doradas',
        'Parque nacional protegido con cascadas impresionantes y lagos alpinos',
        'Chófer profesional con experiencia en las curvas de montaña de Irohazaka',
        'Transporte directo sin colas ni esperas de autobuses públicos',
      ],
      inclusions: [
        '10-12 horas de chófer privado exclusivo',
        'Todos los peajes de autopista a Nikko',
        'Combustible y tarifas de aparcamiento',
        'Agua mineral y Wi-Fi en cabina',
        'Impuestos incluidos (10%)',
      ],
      exclusions: ['Entradas al santuario Toshogu', 'Ascensor de la cascada Kegon', 'Comidas'],
    },
  },

  'yokohama-bay': {
    zh: {
      name: '横滨未来港21・元町中华街与三溪园庭园',
      subtitle: '感受东洋与西洋交融的浪漫港湾与璀璨海景夜市',
      tag: '🌆 港湾璀璨夜景与饕餮美食',
      category: '现代港都与历史风貌',
      overview: '日本开埠历史的现代化浪漫港湾。在日本最大的横滨中华街品尝正宗点心小笼包，漫步于移筑了京都古建筑的三溪园日本名园，傍晚畅游红砖仓库与未来港无敌海景夜景。',
      region: '神奈川县 横滨港区',
      durationText: '东京出发约45分钟',
      whyChooseThis: [
        '距离东京市区仅45分钟，半日或全日轻松游览',
        '直达中华街餐厅正门及三溪园入口',
        '夕阳与夜幕下巡游横滨海湾大桥，尽享绚烂夜景',
        '非常适合家庭聚餐、美食爱好者及情侣出行',
      ],
      inclusions: [
        '6-8小时专属包车服务',
        '首都高速公路通行费',
        '车辆燃油费及停车费',
        '消费税 (10%)',
      ],
      exclusions: ['三溪园门票 (¥700/位)', '餐饮及购物费用', '超时费'],
    },
    fr: {
      name: 'Yokohama Minato Mirai & Quartier Chinois',
      subtitle: 'Élégance Portuaire, Plus Grand Quartier Chinois et Vues Nocturnes',
      tag: '🌆 Vue Nocturne sur la Baie & Gastronomie',
      category: 'Port Historique & Modernité',
      overview: 'Ville portuaire cosmopolite abritant le plus grand quartier chinois du Japon, le splendide jardin traditionnel Sankeien, les entrepôts historiques en brique rouge et la baie illuminée.',
      region: 'Préfecture de Kanagawa',
      durationText: '45 min depuis Tokyo',
      whyChooseThis: [
        'Trajet rapide de 45 minutes depuis Tokyo — parfait pour demi-journée ou soirée',
        'Dépose directe devant les restaurants du quartier chinois et le jardin Sankeien',
        'Traversée nocturne panoramique sur le pont Yokohama Bay Bridge',
        'Idéal pour gourmets, familles et soirées romantiques',
      ],
      inclusions: [
        '6 à 8 heures de mise à disposition avec chauffeur',
        'Péages d’autoroute Shuto',
        'Carburant et parkings',
        'Taxes incluses',
      ],
      exclusions: ['Entrée jardin Sankeien (700 ¥)', 'Repas et achats', 'Heures supplémentaires'],
    },
    es: {
      name: 'Yokohama Minato Mirai y Barrio Chino',
      subtitle: 'La Ciudad Portuaria Internacional, Gastronomía y Vistas Iluminadas',
      tag: '🌆 Luces del Puerto y Gastronomía',
      category: 'Ciudad Portuaria y Vistas',
      overview: 'La emblemática ciudad portuaria internacional de Japón con el barrio chino más grande, el tradicional jardín Sankeien, los almacenes históricos Red Brick y el perfil iluminado de Minato Mirai.',
      region: 'Prefectura de Kanagawa',
      durationText: '45 min desde Tokio',
      whyChooseThis: [
        'A solo 45 minutos de Tokio: perfecto para medio día o noche',
        'Parada directa en la puerta de restaurantes y el jardín Sankeien',
        'Paseo nocturno sobre el emblemático puente colgante Yokohama Bay Bridge',
        'Ideal para amantes de la gastronomía, familias y parejas',
      ],
      inclusions: [
        '6-8 horas de servicio privado exclusivo',
        'Peajes de autopista',
        'Combustible y aparcamiento',
        'Impuestos incluidos',
      ],
      exclusions: ['Entrada a Sankeien (700 ¥)', 'Comidas y compras', 'Horas extras'],
    },
  },

  'karuizawa-retreat': {
    zh: {
      name: '轻井泽皇家避暑胜地・白丝瀑布与王子购物广场',
      subtitle: '日本皇室御用高原避暑胜地与顶级奥特莱斯名牌购物',
      tag: '🌲 高原清幽森林与轻奢购物',
      category: '贵族度假与森林秘境',
      overview: '约翰·列侬与日本皇室深爱的殿堂级高原避暑胜地。游览如白丝般的白丝瀑布、水面如镜的云场池、旧轻井泽银座古街，以及日本顶级轻井泽王子奥特莱斯名牌购物广场。',
      region: '长野县 轻井泽高原',
      durationText: '东京出发约2.5小时',
      whyChooseThis: [
        '宽大后备箱可容纳大量名牌购物战利品与行李',
        '上信越自动车道舒适高原巡航，避暑避寒绝佳之选',
        '自然观光与免税名牌购物自由平衡',
        '东京酒店门到门直达，轻松惬意',
      ],
      inclusions: [
        '10-12小时私人豪华专车包车',
        '关越・上信越高速通行费及白丝收费公路费',
        '燃油费及各处停车费',
        '车内矿泉水与 Wi-Fi',
        '消费税 (10%)',
      ],
      exclusions: ['餐饮及个人购物消费', '超时费用 (¥8,000/小时)'],
    },
    fr: {
      name: 'Karuizawa Retraite Alpine & Centre Commercial Prince',
      subtitle: 'Villégiature Impériale d’Altitude, Cascades et Shopping de Luxe',
      tag: '🌲 Forêts Luxueuses & Shopping',
      category: 'Station Alpine & Villégiature',
      overview: 'Haut lieu de villégiature privilégié par la royauté et John Lennon. Découvrez la cascade de Shiraito, l’étang Kumoba, la vieille rue de Karuizawa et le grand centre Prince Shopping Plaza.',
      region: 'Préfecture de Nagano',
      durationText: '2h30 depuis Tokyo',
      whyChooseThis: [
        'Coffre spacieux pour vos achats outlet et valises d’hiver',
        'Croisière autoroutière sereine vers les hauts plateaux de Nagano',
        'Équilibre idéal entre nature apaisante et boutiques de créateurs',
        'Prise en charge de porte à porte depuis votre hôtel de Tokyo',
      ],
      inclusions: [
        '10 à 12 heures de service VIP avec chauffeur',
        'Péages autoroutiers et route privée de Shiraito',
        'Carburant et parkings',
        'Bouteilles d’eau et Wi-Fi à bord',
        'Taxes incluses',
      ],
      exclusions: ['Repas et achats personnels', 'Heures supplémentaires'],
    },
    es: {
      name: 'Karuizawa Retiro Alpino y Centro Comercial Prince',
      subtitle: 'El Refugio Imperial de Montaña, Cascadas y Compras de Primer Nivel',
      tag: '🌲 Bosques de Lujo y Compras',
      category: 'Resort Alpino y Descanso',
      overview: 'El refugio de montaña predilecto de la realeza y celebridades como John Lennon. Disfrute de la cascada Shiraito, el estanque Kumoba, la histórica calle Ginza de Karuizawa y el centro outlet de lujo.',
      region: 'Prefectura de Nagano',
      durationText: '2.5h desde Tokio',
      whyChooseThis: [
        'Gran capacidad de maletero para compras en outlets y equipaje',
        'Viaje panorámico y confortable por autopista hacia Nagano',
        'Combine naturaleza pura con las mejores firmas internacionales',
        'Recogida y regreso puerta a puerta en su hotel de Tokio',
      ],
      inclusions: [
        '10-12 horas de chófer privado exclusivo',
        'Peajes de autopista y carretera privada de Shiraito',
        'Combustible y aparcamientos',
        'Agua mineral y Wi-Fi en cabina',
        'Impuestos incluidos',
      ],
      exclusions: ['Comidas y compras personales', 'Horas extras'],
    },
  },
};


